### ISSUE TITLE
ImportError: No module named handler

### ISSUE THREAD

**Issue by diranged** [wal-e/wal-e#100]
We're seeing this issue come up with WAL-E 0.6.9 during recovery of a DB:

Traceback (most recent call last):
  File "/usr/local/bin/wal-e", line 9, in <module>
    load_entry_point('wal-e==0.6.9', 'console_scripts', 'wal-e')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 353, in load_entry_point
    def get_metadata(name):
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2321, in load_entry_point
    try:
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2048, in load
    """Parse an entry point group"""
  File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 80, in <module>
    from wal_e.operator import s3_operator
  File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/s3_operator.py", line 10, in <module>
    import wal_e.worker.s3_worker as s3_worker
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/**init**.py", line 3, in <module>
    from wal_e.worker.s3_worker import BackupList
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3_worker.py", line 8, in <module>
    import boto
  File "/usr/local/lib/python2.7/dist-packages/boto/**init**.py", line 28, in <module>
    from boto.storage_uri import BucketStorageUri, FileStorageUri
  File "/usr/local/lib/python2.7/dist-packages/boto/storage_uri.py", line 27, in <module>
    from boto.s3.deletemarker import DeleteMarker
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/**init**.py", line 25, in <module>
    from boto.regioninfo import RegionInfo, get_regions
  File "/usr/local/lib/python2.7/dist-packages/boto/regioninfo.py", line 28, in <module>
    from boto.exception import BotoClientError
  File "/usr/local/lib/python2.7/dist-packages/boto/exception.py", line 28, in <module>
    import xml.sax
  File "/usr/lib/python2.7/xml/sax/**init**.py", line 22, in <module>
    from xmlreader import InputSource
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 4, in <module>
    import handler
ImportError: No module named handler

I know its an XMLReader issue, but I'm not sure why its an issue now in WAL-E... any ideas?

**Comment by diranged** [comment]
@fdr, fyi we just ran into this problem again twice in a row using WAL-E 0.8.0. We hadn't seen it in a long time, so we're still unsure of how it happens. Just an FYI, here's the stack trace:

```++ dirname /mnt/postgres-scripts/wale/wale_restore_command.sh
+ MYPATH=/mnt/postgres-scripts/wale
+ WAL=00000001000027CD0000002D
+ WALDEST=pg_xlog/RECOVERYXLOG
+++ dirname /mnt/postgres-scripts/wale/wale_restore_command.sh
++ cd /mnt/postgres-scripts/wale
++ pwd
+ ENV=/mnt/postgres-scripts/wale/env.sh
+ . /mnt/postgres-scripts/wale/env.sh
++ set +x
AWS Credentials Sourced: /mnt/postgres-scripts/wale/aws.sh
Traceback (most recent call last):
  File "/usr/local/bin/wal-e", line 9, in <module>
    load_entry_point('wal-e==0.8.0', 'console_scripts', 'wal-e')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 356, in load_entry_point
    def get_metadata_lines(name):
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2439, in load_entry_point
    
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2155, in load
    #@property
  File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 96, in <module>
    from wal_e.worker.pg import PSQL_BIN, psql_csv_run
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/__init__.py", line 5, in <module>
    from wal_e.worker.upload import PartitionUploader
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload.py", line 6, in <module>
    import boto.exception
  File "/usr/local/lib/python2.7/dist-packages/boto/__init__.py", line 28, in <module>
    from boto.storage_uri import BucketStorageUri, FileStorageUri
  File "/usr/local/lib/python2.7/dist-packages/boto/storage_uri.py", line 27, in <module>
    from boto.s3.deletemarker import DeleteMarker
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/__init__.py", line 26, in <module>
    from boto.regioninfo import RegionInfo, get_regions
  File "/usr/local/lib/python2.7/dist-packages/boto/regioninfo.py", line 27, in <module>
    from boto.exception import BotoClientError
  File "/usr/local/lib/python2.7/dist-packages/boto/exception.py", line 28, in <module>
    import xml.sax
  File "/usr/lib/python2.7/xml/sax/__init__.py", line 22, in <module>
    from xmlreader import InputSource
ImportError: No module named xmlreader
pg_xlog/RECOVERYXLOG not found. Exiting!
```

**Comment by fdr** [comment]
As before, I'm still mystified.  After all, it's importing boto's exception package, and little more.

**Comment by diranged** [comment]
@Fdr,
  So ya konw what .. this is _still_ happening to us. Its pretty amazing that this bug has stuck around for years for us. We run into it in two different situations. First, we now see it about 95% of the time that we launch a new DB host from scratch, causing us to have to manually go in and force-restart postgres. Secondly, we see it _randomly_ pop up on a host thats been running for months, suddenly requiring a restart of postgres. I still have no solution, but I'm just mentioning it so that you know its still happening. :cry:
