### ISSUE TITLE
backup-fetch: not a lzop file

### ISSUE THREAD

**Issue by james4k** [wal-e/wal-e#133]
```
postgres@vagrant:~$ envdir /etc/wal-e.d/env /usr/local/bin/wal-e backup-fetch /var/lib/postgresql/9.3/main LATEST
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000000.tar.lzo.
        HINT: The absolute S3 key is wal-e/basebackups_005/base_000000010000005B00000084_00000040/tar_partitions/part_00000000.tar.lzo.
        STRUCTURED: time=2014-09-04T20:42:50.880560-00 pid=20155
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000001.tar.lzo.
        HINT: The absolute S3 key is wal-e/basebackups_005/base_000000010000005B00000084_00000040/tar_partitions/part_00000001.tar.lzo.
        STRUCTURED: time=2014-09-04T20:42:50.889421-00 pid=20155
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000002.tar.lzo.
        HINT: The absolute S3 key is wal-e/basebackups_005/base_000000010000005B00000084_00000040/tar_partitions/part_00000002.tar.lzo.
        STRUCTURED: time=2014-09-04T20:42:50.889425-00 pid=20155
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000003.tar.lzo.
        HINT: The absolute S3 key is wal-e/basebackups_005/base_000000010000005B00000084_00000040/tar_partitions/part_00000003.tar.lzo.
        STRUCTURED: time=2014-09-04T20:42:52.603520-00 pid=20155
lzop: <stdin>: not a lzop file
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3/s3_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/tar_partition.py", line 260, in tarfile_extract
            bufsize=pipebuf.PIPE_BUF_BYTES)
          File "/usr/lib/python2.7/tarfile.py", line 1690, in open
            **kwargs)
          File "/usr/lib/python2.7/tarfile.py", line 1574, in __init__
            self.firstmember = self.next()
          File "/usr/lib/python2.7/tarfile.py", line 2334, in next
            raise ReadError("empty file")
        ReadError: empty file

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2014-09-04T20:42:52.721968-00 pid=20155
```

Ubuntu 12.04
Edit: Same story on Ubuntu 14.04

Verified separately via aws CLI that the .tar.lzo's are in fact valid lzop files. backup-list works OK.

Another note: the retries repeatedly continue indefinitely, and instantly, with no apparent falloff of any kind.

Edit: wal-e 0.7.2

**Comment by Yoshi9143** [comment]
+1 to add this as an error message :)

@james4k I have no idea how long this would've taken me were it not for you. If you are in NYC, I'm buying you coffee/beverage of your choice.
