### ISSUE TITLE
requirements.txt should include six

### ISSUE THREAD

**Issue by AgDude** [wal-e/wal-e#143]
I installed wal-e on a fresh system running Ubuntu 14.04 using pip. The included version of "six" was causing this error on running wal-e

```
Traceback (most recent call last):
  File "/usr/local/bin/wal-e", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2880, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 434, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 447, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six>=1.7.0
```

Upgrading six solved the problem, but that should have been handled by pip.

`pip install --upgrade six`

**Comment by sbecker** [comment]
This is still an issue. Without "six" >= 1.7.0, on a fresh Ubuntu box, wal-e throws a stack trace.

**Comment by codyhatch** [comment]
Ran into this issue on a fresh 14.04 box.

**Comment by fdr** [comment]
Can you show the stack trace?

**Comment by fdr** [comment]
I'm a little perplexed where the "six" dependency is coming in.  Maybe I'll have to bite the bullet, but I'm suspecting a dependency.

**Comment by fdr** [comment]
Also, if you can try omitting some/one of the other dependencies (I cast a weary eye on OpenStack in particular, just because somehow its client is incredibly complex) to see if you can eliminate the issue, that'd also be appreciated.

**Comment by codyhatch** [comment]
```
$ wal-e
Traceback (most recent call last):
  File "/usr/local/bin/wal-e", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six>=1.7.0
```

Which doesn't look like a wal-e issue, really.  But wal-e is breaking, and everything else on the system seems to work, so...is there anything I can do to narrow down what's causing the issue?

**Comment by fdr** [comment]
Try adjusting requirements.txt to eliminate OpenStack's root dependency, and see if you can install then.  Repeat for other drivers/dependencies one at a time.

**Comment by nremond** [comment]
On a fresh Ubuntu 14.04, I got the same issue wit `six`. But then, after upgrading, I had to this `pkg_resources.DistributionNotFound: netifaces>=0.10.4`.

So, I had to upgrade `six`+`netifaces` packages.

**Comment by iCyberon** [comment]
Same here, fresh Ubuntu 14.04.

```
unknown@Unknown:~$ pip install --upgrade requests
unknown@Unknown:~$ pip install --upgrade six
```

Worked only after I upgraded ```requests``` and ```six```.

**Comment by thom-nic** [comment]
I got here via Stouts/Stouts.wale#14, on a stock Ubuntu Server Trusty (14.04).  wal-e version=latest is installed via pip.  It seems as @iCyberon pointed out, not only does `six` need to be manually installed but also `requests`:

```
Traceback (most recent call last):
  File "/usr/local/bin/wal-e", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.8.1,!=2.9.0"
```

**Comment by louissimps** [comment]
@iCyberon that did it for me, thanks
