### ISSUE TITLE
S3 upload errors

### ISSUE THREAD

**Issue by marclennox** [wal-e/wal-e#164]
I'm getting the following error from one of my servers, which is confusing because my other servers don't exhibit this error.  Any clues how to debug it?

What is the fully qualified name that is used for the s3:// uri prefix?

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/wal_e/worker/upload.py", line 43, in __call__
    self.gpg_key_id)
  File "/usr/local/lib/python2.7/site-packages/wal_e/worker/worker_util.py", line 40, in do_lzop_put
    k = blobstore.uri_put_file(creds, url, tf)
  File "/usr/local/lib/python2.7/site-packages/wal_e/blobstore/s3/s3_util.py", line 54, in uri_put_file
    k.set_contents_from_file(fp)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1070, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1029, in _mexe
    raise ex
gaierror: [Errno -2] Name or service not known
<Greenlet at 0x7f8f93efac30: <wal_e.worker.upload.WalUploader object at 0x7f8f93a47550>(<wal_e.worker.pg.wal_transfer.WalSegment object at)> failed with gaierror

wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/site-packages/wal_e/cmd.py", line 553, in main
            concurrency=args.pool_size)
          File "/usr/local/lib/python2.7/site-packages/wal_e/operator/backup.py", line 281, in wal_archive
            group.join()
          File "/usr/local/lib/python2.7/site-packages/wal_e/worker/pg/wal_transfer.py", line 121, in join
            raise val
        gaierror: [Errno -2] Name or service not known

        STRUCTURED: time=2015-02-17T19:52:36.970048-00 pid=275
```

**Comment by marclennox** [comment]
Apologies, this is a DNS problem inside of my Docker container that is running Postgresql.
