### ISSUE TITLE
Incorrect version of six ?

### ISSUE THREAD

**Issue by nremond** [wal-e/wal-e#166]
Hi,

I'm install WAL-E on a fresh installation of Ubuntu 14.04 Server by doing : `pip install -e git+git://github.com/wal-e/wal-e.git@#egg=wal-e`

Then, I end up with the following error:

```
nremond@db01:~$ wal-e
Traceback (most recent call last):
  File "/usr/local/bin/wal-e", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six>=1.7.0
```

Also, 
```
nremond@db01:~$ pip show six
---
Name: six
Version: 1.5.2
Location: /usr/lib/python2.7/dist-packages
Requires:
```

Any clue? I'm not so familiar with Python packaging.
Can I provide you with more informations ?

thank you
Nicolas

**Comment by nremond** [comment]
same as #143, sorry for the noise.
