### ISSUE TITLE
lzop: <stdin>: Compressed data violation

### ISSUE THREAD

**Issue by vmihailenco** [wal-e/wal-e#172]
Do you have any recommendations how to debug this? We use v0.8c1, but v0.8 fails with similar exception. Previously WAL-E worked fine for us.

```
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000004.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_000000010000069300000083_00232840/tar_partitions/part_00000004.tar.lzo.
        STRUCTURED: time=2015-03-29T14:47:44.911781-00 pid=18002
requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (2): snet-storage101.ord1.clouddrive.com
/var/lib/postgresql/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000005.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_000000010000069300000083_00232840/tar_partitions/part_00000005.tar.lzo.
        STRUCTURED: time=2015-03-29T14:47:45.278930-00 pid=18002
lzop: <stdin>: Compressed data violation
lzop: <stdin>: Compressed data violation
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/var/lib/postgresql/venv/local/lib/python2.7/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/var/lib/postgresql/venv/local/lib/python2.7/site-packages/wal_e/worker/swift/swift_worker.py", line 78, in fetch_partition
            raise exc
        OSError: [Errno 32] Broken pipe

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2015-03-29T14:47:45.839374-00 pid=18002
```

**Comment by vmihailenco** [comment]
Another example:

```
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000004.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_000000010000069300000083_00232840/tar_partitions/part_00000004.tar.lzo.
        STRUCTURED: time=2015-03-29T14:59:55.487123-00 pid=19116
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000005.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_000000010000069300000083_00232840/tar_partitions/part_00000005.tar.lzo.
        STRUCTURED: time=2015-03-29T15:00:00.690914-00 pid=19116
requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (2): storage101.ord1.clouddrive.com
/var/lib/postgresql/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
lzop: Inappropriate ioctl for device: <stdin>
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/var/lib/postgresql/venv/local/lib/python2.7/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/var/lib/postgresql/venv/local/lib/python2.7/site-packages/wal_e/worker/swift/swift_worker.py", line 78, in fetch_partition
            raise exc
        AssertionError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.hub.Waiter object at 0x7f48d1f6d640>>

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2015-03-29T15:00:01.450705-00 pid=19116
```

**Comment by vmihailenco** [comment]
Downgrading python-swiftclient from 2.4.0 to 2.3.1 fixed the issue. Can you please lock swiftclient version used with WAL-E?

**Comment by vmihailenco** [comment]
Reported swiftclient bug at https://bugs.launchpad.net/swift/+bug/1437870

**Comment by vmihailenco** [comment]
Same issue https://groups.google.com/forum/#!topic/wal-e/KfE3WEyTszg

**Comment by fdr** [comment]
Thanks for chasing this up.  I fear this is somehow related to use of gevent, which is starting to look dodgier and dodgier, but is not trivial to remove (but, probably possible).

**Comment by fdr** [comment]
Seems like this was a bug in Swiftclient or a change in Rackspace per the thread linked.
