### ISSUE TITLE
backup-list fails with 'module' object has no attribute 'sslwrap'

### ISSUE THREAD

**Issue by seanlinsley** [wal-e/wal-e#176]
On a Mac, with this setup:
```sh
$ brew install daemontools lzop pv
$ pip install wal-e
$ wal-e version
0.8.0
```
I get this error when running `backup-list`:
```sh
$ envdir .env wal-e backup-list
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-list".
        STRUCTURED: time=2015-04-21T17:25:07.537474-00 pid=59121
name  last_modified expanded_size_bytes wal_segment_backup_start  wal_segment_offset_backup_start wal_segment_backup_stop wal_segment_offset_backup_stop
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/site-packages/wal_e/cmd.py", line 547, in main
            backup_cxt.backup_list(query=args.QUERY, detail=args.detail)
          File "/usr/local/lib/python2.7/site-packages/wal_e/operator/backup.py", line 66, in backup_list
            for bi in bl_iter:
          File "/usr/local/lib/python2.7/site-packages/wal_e/worker/base.py", line 153, in __iter__
            for key in self._backup_list(self.layout.basebackups()):
          File "/usr/local/lib/python2.7/site-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
            encoding_type=encoding_type)
          File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 472, in get_all_keys
            '', headers, **params)
          File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 398, in _get_all
            query_args=query_args)
          File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
            retry_handler=retry_handler
          File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
            retry_handler=retry_handler)
          File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 943, in _mexe
            request.body, request.headers)
          File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in request
            self._send_request(method, url, body, headers)
          File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1035, in _send_request
            self.endheaders(body)
          File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 997, in endheaders
            self._send_output(message_body)
          File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 850, in _send_output
            self.send(msg)
          File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 812, in send
            self.connect()
          File "/usr/local/lib/python2.7/site-packages/boto/https_connection.py", line 131, in connect
            ca_certs=self.ca_certs)
          File "/usr/local/lib/python2.7/site-packages/wal_e/cmd.py", line 76, in wrap_socket_monkey
            return original(*args, **kwargs)
          File "/usr/local/lib/python2.7/site-packages/gevent/ssl.py", line 383, in wrap_socket
            ciphers=ciphers)
          File "/usr/local/lib/python2.7/site-packages/gevent/ssl.py", line 89, in __init__
            self._sslobj = _ssl.sslwrap(self._sock, server_side,
        AttributeError: 'module' object has no attribute 'sslwrap'
        
        STRUCTURED: time=2015-04-21T17:25:10.798370-00 pid=59121
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 861, in emit
    self.socket.send(msg)
  File "/usr/local/lib/python2.7/site-packages/gevent/socket.py", line 435, in send
    return sock.send(data, flags)
error: [Errno 40] Message too long
Logged from file log_help.py, line 189
```

**Comment by fdr** [comment]
Ah. That's gevent being totally busted with Pythons with certain backports (e.g. in Ubuntu Utopic at least) or the 2.7.9 point release. https://github.com/gevent/gevent/issues/477.

Running 2.7.8 should fix it, e.g. with pyenv.

I've been rather hoping it'd be fixed by now (as the bug as opened in September), but it's definitely getting long in the tooth and quite worrisome.

**Comment by fdr** [comment]
This is fixed with newer gevents.

**Comment by seanlinsley** [comment]
Indeed it is. Thanks for the update :cat:
