### ISSUE TITLE
Error while deleting backups on GCE with S3 interoperable access

### ISSUE THREAD

**Issue by keymon** [wal-e/wal-e#192]
We are using GCE in S3 interoperable access.

So far all the features of WAL-E work, except delete the backups. It fails with this error. This issue was [reported before as a comment by @russss](https://github.com/wal-e/wal-e/issues/122#issuecomment-121952012) in the context of #122 , but here I want to report the specific issue with S3 protocol on GCE.

```
 HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2015-07-30T16:26:21.219809-00 pid=21619
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3/s3_deleter.py", line 27, in _delete_batch
            bucket.delete_keys([key.name for key in page])
          File "/usr/lib/python2.7/dist-packages/boto/s3/bucket.py", line 602, in delete_keys
            while delete_keys2(headers):
          File "/usr/lib/python2.7/dist-packages/boto/s3/bucket.py", line 601, in delete_keys2
            body)
        S3ResponseError: S3ResponseError: 400 Bad Request
        <?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message><Details>Cannot create buckets using a POST.</Details></Error>
```

We researched the issue, and we think that the root cause is that GCE does not support or implements differently [the multi-object delete api from S3](http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html). Unfortunately  I was not able to find references about the support of GCE of this API. 

This API to delete keys in batch is used by the boto library in the function [Bucket.delete_keys()](https://github.com/boto/boto/blob/develop/boto/s3/bucket.py#L666-731) which is used by WAL-E [in the S3 Deleter()](https://github.com/wal-e/wal-e/blob/master/wal_e/worker/s3/s3_deleter.py#L27--1).

This could be consider a problem in the boto library, but we can also workaround it in WAL-E by using [bucket.delete()](https://github.com/boto/boto/blob/develop/boto/s3/bucket.py#L731--1). 

We are going to do a corresponding PR soon.

**Comment by keymon** [comment]
Some related comments about this:
 * http://stackoverflow.com/questions/26349901/delete-all-files-in-folder-or-with-prefix-in-google-cloud-bucket-from-java
