### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by WillPlatnick** [wal-e/wal-e#208]
Hello,
I am using WAL-E to backup to SoftLayer's object store using swift.  I am using WAL-E successfully on 2 servers, but on this one, I get connection reset errors. Is there a way for WAL-E to retry if there's a reset connection with SoftLayer? I also have no idea why the connection is being reset, we backup two other servers to the same store at the same time and don't have these issues, and the NIC diagnostics and iptables look fine...plus everything is running super smoothly on this database server.

```
requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): dal05.objectstorage.service.networklayer.com
requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): dal05.objectstorage.service.networklayer.com
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload.py", line 144, in __call__
    k = put_file_helper()
  File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 72, in shim
    exc_processor_cxt=exc_processor_cxt)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 104, in retry_with_count_internal
    side_effect_func(exc_tup, exc_processor_cxt)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload.py", line 139, in put_file_helper
    return self.blobstore.uri_put_file(self.creds, url, tf)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/blobstore/swift/utils.py", line 37, in uri_put_file
    container_name, url_tup.path, fp, content_type=content_encoding
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1369, in put_object
    response_dict=response_dict)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1243, in _retry
    rv = func(self.url, self.token, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 993, in put_object
    conn.putrequest(path, headers=headers, data=chunk_reader())
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 227, in putrequest
    return self.request('PUT', full_path, data, headers, files)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 217, in request
    files=files, **self.requests_args)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 185, in _request
    return self.request_session.request(*arg, **kwarg)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 408, in send
    low_conn.close()
  File "/usr/lib/python2.7/httplib.py", line 765, in close
    self.sock.close()   # close it manually... there may be other refs
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 213, in close
    return self.connection.shutdown()
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1522, in shutdown
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1178, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (104, 'ECONNRESET')
<Greenlet at 0x2068370: <wal_e.worker.upload.PartitionUploader object at 0x205e550>([ExtendedTarInfo(submitted_path='/ssd/pgsqldata/ba)> failed with SysCallError

wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2015-11-08T08:08:50.246090-00 pid=23170
NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 572, in main
            pool_size=args.pool_size)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 197, in database_backup
            **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 502, in _upload_pg_cluster_dir
            pool.put(tpart)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload_pool.py", line 108, in put
            self._wait()
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload_pool.py", line 65, in _wait
            raise val
        SysCallError: (104, 'ECONNRESET')
        
        STRUCTURED: time=2015-11-08T08:08:52.326030-00 pid=23170
```

**Comment by bshi** [comment]
Going by the git-blame, @alex may be the right person to ping to get help/feedback as he seems to be the original author.

**Comment by WillPlatnick** [comment]
@alex, do you have any thoughts on this?

**Comment by alex** [comment]
I've never seen this error before, so I can't claim to have any particular insight.
