### ISSUE TITLE
getting 403 forbidden when running delete

### ISSUE THREAD

**Issue by pdeva** [wal-e/wal-e#223]
Here is the output:

```
/usr/bin/envdir /etc/wal-e.d/env /usr/local/bin/wal-e delete --confirm retain 50
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "delete retain".
        STRUCTURED: time=2016-03-03T03:55:56.261473-00 pid=14141
wal_e.main   INFO     MSG: deleting data in the store
        STRUCTURED: time=2016-03-03T03:55:56.270378-00 pid=14141
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 620, in main
            args.NUM_TO_RETAIN)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 425, in delete_with_retention
            delete_cxt.delete_with_retention(num_to_retain)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/base.py", line 446, in delete_with_retention
            for key in self._backup_list(prefix=self.layout.basebackups()):
          File "/usr/lib/python2.7/dist-packages/boto/s3/bucketlistresultset.py", line 30, in bucket_lister
            delimiter=delimiter, headers=headers)
          File "/usr/lib/python2.7/dist-packages/boto/s3/bucket.py", line 392, in get_all_keys
            '', headers, **params)
          File "/usr/lib/python2.7/dist-packages/boto/s3/bucket.py", line 343, in _get_all
            response.status, response.reason, body)
        S3ResponseError: S3ResponseError: 403 Forbidden

```

I have given all permissions to the IAM user:

```
           "Effect": "Allow",
            "Action": [
                "s3:*"
            ]
```

Both push and fetch are working. only delete isnt.
Could this be a bug a in wal-e?

Using wal-e 0.8.1 on ubuntu 14.04

**Comment by pdeva** [comment]
ok figured it out.
apparently if you store your backups in bucket `a/b`, you cant just given permission to `a/b`, you need to also give permission to parent bucket `a`
