### ISSUE TITLE
push backups to s3 fails after upgrading from 0.8.1 to 0.9.0

### ISSUE THREAD

**Issue by PKiman** [wal-e/wal-e#231]
After upgrading wal-e from 0.8.1 to 0.9.0 the command fails with the following error:
For now I reverted back to version 0.8.1.
```
bash-4.2$ /usr/local/bin/envdir /etc/wal-e.d/env /usr/local/bin/wal-e backup-push /var/lib/pgsql94/data
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2016-03-29T15:22:52.941990-00 pid=16231
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.6/site-packages/wal_e/cmd.py", line 566, in main
            external_program_check(external_programs)
          File "/usr/local/lib/python2.6/site-packages/wal_e/cmd.py", line 137, in external_program_check
            psql_csv_run('SELECT 1', error_handler=psql_err_handler)
          File "/usr/local/lib/python2.6/site-packages/wal_e/worker/pg/psql_worker.py", line 43, in psql_csv_run
            csv_query.append('COPY ({}) TO STDOUT WITH CSV HEADER'.format(sql_command))
        ValueError: zero length field name in format
        
        STRUCTURED: time=2016-03-29T15:22:52.981438-00 pid=16231
bash-4.2$ /usr/local/bin/envdir /etc/wal-e.d/env /usr/local/bin/wal-e backup-push /var/lib/pgsql94/data
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2016-03-29T15:31:05.211876-00 pid=16994
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.6/site-packages/wal_e/cmd.py", line 566, in main
            external_program_check(external_programs)
          File "/usr/local/lib/python2.6/site-packages/wal_e/cmd.py", line 137, in external_program_check
            psql_csv_run('SELECT 1', error_handler=psql_err_handler)
          File "/usr/local/lib/python2.6/site-packages/wal_e/worker/pg/psql_worker.py", line 43, in psql_csv_run
            csv_query.append('COPY ({}) TO STDOUT WITH CSV HEADER'.format(sql_command))
        ValueError: zero length field name in format

```

**Comment by fdr** [comment]
That's a python compatibility bug, you are probably running Python 2.6, yes? It is no longer supported, because some of my dependencies also do not support it anymore. WAL-E should give a better error message, though...

**Comment by PKiman** [comment]
Excellent! This hint works. 
Thanks,
Paul
