### ISSUE TITLE
Failure after installing from pip

### ISSUE THREAD

**Issue by centromere** [wal-e/wal-e#246]
I get the following error after installing from pip on Ubuntu 14.04:

```
Traceback (most recent call last):
  File "/usr/local/bin/wal-e", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.8.1,!=2.9.0
```

**Comment by Aitem** [comment]
+1 same problem

**Comment by earsdown** [comment]
Hi @Aitem , I also ran into this bug. My workaround was to add the `--upgrade` option to pip install.

**Comment by rodo** [comment]
This bug is related to pip, reinstall or upgrade, see #241 it's the same.
Sometimes you can just upgrade distribute too

**Comment by fdr** [comment]
Unfortunately upstream dependencies break WAL-E installs all the time. The problem is getting worse as more backends are added. A more satisfying mitigation that could be done in WAL-E is to start making backends optional.

They are already lazily-loaded, so this is mostly packaging work and adding good error messages on import failures.
