### ISSUE TITLE
Server becomes unresponsive around time of wal-e exception

### ISSUE THREAD

**Issue by ckbhodge** [wal-e/wal-e#255]
I'm not sure if this is actually caused by wal-e or not, so I apologize if this is in the wrong place!

I'm running Postgres 9.3 on EC2 and have some occasional times where the server becomes unresponsive (CloudWatch says as much, I can't connect to the server via SSH).  When I check the pg logs, the only commonality between these times is that wal-e had an exception:

```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload.py", line 50, in __call__
    self.gpg_key_id)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/worker_util.py", line 40, in do_lzop_put
    k = blobstore.uri_put_file(creds, url, tf)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/blobstore/s3/s3_util.py", line 55, in uri_put_file
    k.set_contents_from_file(fp, encrypt_key=True)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
gaierror: [Errno -2] Name or service not known
<Greenlet at 0x7ff6529f3870: <wal_e.worker.upload.WalUploader object at 0x7ff6527460d0>(<wal_e.worker.pg.wal_transfer.WalSegment object at)> failed with gaierror

wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 586, in main
            concurrency=args.pool_size)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 285, in wal_archive
            group.join()
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/pg/wal_transfer.py", line 144, in join
            raise val
        gaierror: [Errno -2] Name or service not known
        
        STRUCTURED: time=2016-06-27T04:06:19.046691-00 pid=19614
2016-06-27 04:06:19.057 UTC LOG:  archive command failed with exit code 2
2016-06-27 04:06:19.057 UTC DETAIL:  The failed archive command was: envdir /etc/wal-e.d/env /usr/local/bin/wal-e wal-push pg_xlog/00000001000008980000002B
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-push".
        STRUCTURED: time=2016-06-27T04:06:20.140475-00 pid=19634
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/00000001000008980000002B" to "s3://sql-backup-omitted-com/wal_005/00000001000008980000002B.lzo".
        STRUCTURED: time=2016-06-27T04:06:20.153115-00 pid=19634 action=push-wal key=s3://sql-backup-omitted-com/wal_005/00000001000008980000002B.lzo prefix= seg=00000001000008980000002B state=begin
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/00000001000008980000002C" to "s3://sql-backup-omitted-com/wal_005/00000001000008980000002C.lzo".
        STRUCTURED: time=2016-06-27T04:06:20.155220-00 pid=19634 action=push-wal key=s3://sql-backup-omitted-com/wal_005/00000001000008980000002C.lzo prefix= seg=00000001000008980000002C state=begin
2016-06-27 04:08:30.987 UTC LOG:  checkpoint complete: wrote 2814 buffers (1.1%); 0 transaction log file(s) added, 0 removed, 5 recycled; write=209.668 s, sync=0.050 s, total=209.732 s; sync files=139, longest=0.008 s, average=0.000 s
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload.py", line 50, in __call__
    self.gpg_key_id)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/worker_util.py", line 40, in do_lzop_put
    k = blobstore.uri_put_file(creds, url, tf)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/blobstore/s3/s3_util.py", line 55, in uri_put_file
    k.set_contents_from_file(fp, encrypt_key=True)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
gaierror: [Errno -2] Name or service not known
<Greenlet at 0x7f97e51b3870: <wal_e.worker.upload.WalUploader object at 0x7f97e4f060d0>(<wal_e.worker.pg.wal_transfer.WalSegment object at)> failed with gaierror

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload.py", line 50, in __call__
    self.gpg_key_id)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/worker_util.py", line 40, in do_lzop_put
    k = blobstore.uri_put_file(creds, url, tf)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/blobstore/s3/s3_util.py", line 55, in uri_put_file
    k.set_contents_from_file(fp, encrypt_key=True)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
gaierror: [Errno -2] Name or service not known
<Greenlet at 0x7f97e51b3cd0: <wal_e.worker.upload.WalUploader object at 0x7f97e4f060d0>(<wal_e.worker.pg.wal_transfer.WalSegment object at)> failed with gaierror

wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 586, in main
            concurrency=args.pool_size)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 285, in wal_archive
            group.join()
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/pg/wal_transfer.py", line 144, in join
            raise val
        gaierror: [Errno -2] Name or service not known
        
        STRUCTURED: time=2016-06-27T04:09:04.722245-00 pid=19634
2016-06-27 04:09:04.733 UTC LOG:  archive command failed with exit code 2
2016-06-27 04:09:04.733 UTC DETAIL:  The failed archive command was: envdir /etc/wal-e.d/env /usr/local/bin/wal-e wal-push pg_xlog/00000001000008980000002B
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-push".
        STRUCTURED: time=2016-06-27T04:09:05.816558-00 pid=19654
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/00000001000008980000002B" to "s3://sql-backup-omitted-com/wal_005/00000001000008980000002B.lzo".
        STRUCTURED: time=2016-06-27T04:09:05.829202-00 pid=19654 action=push-wal key=s3://sql-backup-omitted-com/wal_005/00000001000008980000002B.lzo prefix= seg=00000001000008980000002B state=begin
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/00000001000008980000002C" to "s3://sql-backup-omitted-com/wal_005/00000001000008980000002C.lzo".
        STRUCTURED: time=2016-06-27T04:09:05.831307-00 pid=19654 action=push-wal key=s3://sql-backup-omitted-com/wal_005/00000001000008980000002C.lzo prefix= seg=00000001000008980000002C state=begin
```

Has anyone else seen this behavior?

**Comment by fdr** [comment]
Looks like you are losing DNS resolution. I think WAL-E is merely noticing this first, but your server is about to go kaput.

There's a few possible mechanisms for this. One is that network access is coming apart, and resolving hostnames is among the first steps in wal-e's network connectivity processes.

A second is that you may be encountering DNS throttling issues. I'm not sure why that would make your system unresponsive, but a number of programs do not cope with untimely resolutions well. To experiment with fixing that, I'd suggest 'dnsmasq' caching.
