### ISSUE TITLE
backup-push to S3 error: timed out? SSL?

### ISSUE THREAD

**Issue by davidham** [wal-e/wal-e#256]
After restoring with PITR, I am trying to do a new `backup-push`, but I am getting errors that the operation has timed out. 

Here's the output after running `backup-push`:

```
root@1b7016f29155:/# gosu postgres envdir /etc/wal-e.d/env /opt/wale/bin/wal-e backup-push $PGDATA                                             
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2016-06-29T14:53:46.143174-00 pid=119
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to s3://redacted/postgres-backup/basebackups_005/base_0000000B0000005E00000010_00000096/extended_version.txt.
        STRUCTURED: time=2016-06-29T14:53:46.538699-00 pid=119
wal_e.operator.backup INFO     MSG: postgres version metadata upload complete
        STRUCTURED: time=2016-06-29T14:53:47.584600-00 pid=119
wal_e.worker.upload INFO     MSG: beginning volume compression
        DETAIL: Building volume 0.
        STRUCTURED: time=2016-06-29T14:53:47.695502-00 pid=119
wal_e.worker.upload INFO     MSG: begin uploading a base backup volume
        DETAIL: Uploading to "s3://redacted/postgres-backup/basebackups_005/base_0000000B0000005E00000010_00000096/tar_partitions/part_00000000.tar.lzo".
        STRUCTURED: time=2016-06-29T14:53:48.457407-00 pid=119
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '('timed out',)'.  There have been 1 attempts to send the volume 0 so far.
        STRUCTURED: time=2016-06-29T14:56:19.281416-00 pid=119
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '('timed out',)'.  There have been 2 attempts to send the volume 0 so far.
        STRUCTURED: time=2016-06-29T14:58:47.945441-00 pid=119
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '('timed out',)'.  There have been 3 attempts to send the volume 0 so far.
        STRUCTURED: time=2016-06-29T15:01:04.359100-00 pid=119
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '('timed out',)'.  There have been 4 attempts to send the volume 0 so far.
        STRUCTURED: time=2016-06-29T15:03:15.136338-00 pid=119
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '('timed out',)'.  There have been 5 attempts to send the volume 0 so far.
        STRUCTURED: time=2016-06-29T15:04:45.058957-00 pid=119
```

Here's some stdout from Postgres while this is happening:
```
postgres_1  | Traceback (most recent call last):
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
postgres_1  |     result = self._run(*self.args, **self.kwargs)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/wal_e/worker/upload.py", line 50, in __call__
postgres_1  |     self.gpg_key_id)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/wal_e/worker/worker_util.py", line 40, in do_lzop_put
postgres_1  |     k = blobstore.uri_put_file(creds, url, tf)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/wal_e/blobstore/s3/s3_util.py", line 57, in uri_put_file
postgres_1  |     k.set_contents_from_file(fp, encrypt_key=True)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
postgres_1  |     chunked_transfer=chunked_transfer, size=size)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
postgres_1  |     chunked_transfer=chunked_transfer, size=size)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
postgres_1  |     query_args=query_args
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/connection.py", line 668, in make_request
postgres_1  |     retry_handler=retry_handler
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
postgres_1  |     retry_handler=retry_handler)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
postgres_1  |     raise ex
postgres_1  | SSLError: ('The read operation timed out',)
postgres_1  | <Greenlet at 0x7f3233ffa7d0: <wal_e.worker.upload.WalUploader object at 0x7f3233d3f090>(<wal_e.worker.pg.wal_transfer.WalSegment object at)> failed with SSLError
postgres_1  | 
postgres_1  | Traceback (most recent call last):
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
postgres_1  |     result = self._run(*self.args, **self.kwargs)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/wal_e/worker/upload.py", line 50, in __call__
postgres_1  |     self.gpg_key_id)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/wal_e/worker/worker_util.py", line 40, in do_lzop_put
postgres_1  |     k = blobstore.uri_put_file(creds, url, tf)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/wal_e/blobstore/s3/s3_util.py", line 57, in uri_put_file
postgres_1  |     k.set_contents_from_file(fp, encrypt_key=True)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
postgres_1  |     chunked_transfer=chunked_transfer, size=size)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
postgres_1  |     chunked_transfer=chunked_transfer, size=size)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
postgres_1  |     query_args=query_args
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/connection.py", line 668, in make_request
postgres_1  |     retry_handler=retry_handler
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
postgres_1  |     retry_handler=retry_handler)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
postgres_1  |     raise ex
postgres_1  | SSLError: ('The read operation timed out',)
postgres_1  | <Greenlet at 0x7f3233ffa4b0: <wal_e.worker.upload.WalUploader object at 0x7f3233d3f090>(<wal_e.worker.pg.wal_transfer.WalSegment object at)> failed with SSLError
postgres_1  | 
postgres_1  | Traceback (most recent call last):
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
postgres_1  |     result = self._run(*self.args, **self.kwargs)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/wal_e/worker/upload.py", line 50, in __call__
postgres_1  |     self.gpg_key_id)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/wal_e/worker/worker_util.py", line 40, in do_lzop_put
postgres_1  |     k = blobstore.uri_put_file(creds, url, tf)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/wal_e/blobstore/s3/s3_util.py", line 57, in uri_put_file
postgres_1  |     k.set_contents_from_file(fp, encrypt_key=True)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
postgres_1  |     chunked_transfer=chunked_transfer, size=size)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
postgres_1  |     chunked_transfer=chunked_transfer, size=size)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
postgres_1  |     query_args=query_args
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/s3/connection.py", line 668, in make_request
postgres_1  |     retry_handler=retry_handler
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
postgres_1  |     retry_handler=retry_handler)
postgres_1  |   File "/opt/wale/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
postgres_1  |     raise ex
postgres_1  | SSLError: ('The read operation timed out',)
postgres_1  | <Greenlet at 0x7f3233ffa550: <wal_e.worker.upload.WalUploader object at 0x7f3233d3f090>(<wal_e.worker.pg.wal_transfer.WalSegment object at)> failed with SSLError
postgres_1  | 
postgres_1  | wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
postgres_1  |         DETAIL: Traceback (most recent call last):
postgres_1  |           File "/opt/wale/local/lib/python2.7/site-packages/wal_e/cmd.py", line 592, in main
postgres_1  |             concurrency=args.pool_size)
postgres_1  |           File "/opt/wale/local/lib/python2.7/site-packages/wal_e/operator/backup.py", line 285, in wal_archive
postgres_1  |             group.join()
postgres_1  |           File "/opt/wale/local/lib/python2.7/site-packages/wal_e/worker/pg/wal_transfer.py", line 144, in join
postgres_1  |             raise val
postgres_1  |         SSLError: ('The read operation timed out',)
postgres_1  |         
postgres_1  |         STRUCTURED: time=2016-06-29T15:06:40.436707-00 pid=258
postgres_1  | LOG:  archive command failed with exit code 2
```

The SSL connection worked when I was restoring the backup, and it worked previously--there are backups present on the target S3 bucket.

I had made a mistake and sent WAL logs from the wrong environment into my development backup bucket, and that's why I needed to do PITR. Would that have anything to do with these errors?

Here are my config settings:

```
wal_level = hot_standby;
archive_mode = on;
archive_command = "envdir /etc/wal-e.d/env /opt/wale/bin/wal-e wal-push %p";
archive_timeout = 60;
```

Running on the postgres:9.4 docker image.

Thanks for any help you can offer.

**Comment by fdr** [comment]
I've seen these kinds of errors for a number of reasons: high load, cross-region replication, newly created buckets, bad credentials. If you mentioned sending WAL from "the wrong environment", I'd suspect credentials.
