### ISSUE TITLE
WABS Backup failing with "unprocessed exception has avoided all error handling"

### ISSUE THREAD

**Issue by bmleshopventory** [wal-e/wal-e#257]
The logs look like this: 

```
Jul 25 21:36:26 sv-db1 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): svproddbbackup.blob.core.windows.net
Jul 25 21:36:27 sv-db1 wal_e.worker.upload INFO     MSG: completed archiving to a file#012        DETAIL: Archiving to "wabs://db-backup/wal_005/0000000500003313000000D5.00000028.backup.lzo" complete at 00KiB/s.#012        STRUCTURED: time=2016-07-26T01:36:27.035835-00 pid=28070 action=push-wal key=wabs://db-backup/wal_005/0000000500003313000000D5.00000028.backup.lzo prefix= rate=00 seg=0000000500003313000000D5.00000028.backup state=complete
Jul 25 21:36:27 sv-db1 wal_e.blobstore.wabs.wabs_util WARNING  MSG: retrying file upload from unexpected exception#012        DETAIL: The exception type is <class 'select.error'> and its value is (4, 'Interrupted system call') and its traceback is   File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim#012            return f(*args, **kwargs)#012          File "/usr/local/lib/python2.7/dist-packages/wal_e/blobstore/wabs/wabs_util.py", line 90, in upload_chunk#012            block_id, content_md5=check_sum)#012          File "/usr/local/lib/python2.7/dist-packages/azure/storage/blob/blobservice.py", line 2366, in put_block#012            self._perform_request(request)#012          File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 171, in _perform_request#012            resp = self._filter(request)#012          File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 160, in _perform_request_worker#012            return self._httpclient.perform_request(request)#012          File "/usr/local/lib/python2.7/dist-packages/azure/storage/_http/httpclient.py", line 181, in perform_request#012            self.send_request_body(connection, request.body)#012          File "/usr/local/lib/python2.7/dist-packages/azure/storage/_http/httpclient.py", line 143, in send_request_body#012            connection.send(request_body)#012          File "/usr/local/lib/python2.7/dist-packages/azure/storage/_http/requestsclient.py", line 81, in send#012            self.response = self.session.request(self.method, self.uri, data=request_body, headers=self.headers, timeout=self.timeout)#012          File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request#012            resp = self.send(prep, **send_kwargs)#012          File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send#012            r = adapter.send(request, **kwargs)#012          File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 403, in send#012            timeout=timeout#012          File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen#012            chunked=chunked)#012          File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request#012            httplib_response = conn.getresponse(buffering=True)#012          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 32, in monkey#012            return original(*args, **kwargs)#012          File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse#012            response.begin()#012          File "/usr/lib/python2.7/httplib.py", line 415, in begin#012            version, status, reason = self._read_status()#012          File "/usr/lib/python2.7/httplib.py", line 371, in _read_status#012            line = self.fp.readline(_MAXLINE + 1)#012          File "/usr/lib/python2.7/socket.py", line 476, in readline#012            data = self._sock.recv(self._rbufsize)#012          File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 207, in recv#012            [self.socket], [], [], self.socket.gettimeout())#012          There have been 1 attempts to upload  file wabs://db-backup/basebackups_005/base_0000000500003313000000D5_00000040/tar_partitions/part_00000228.tar.lzo so far.#012        STRUCTURED: time=2016-07-26T01:36:27.306487-00 pid=20812
Jul 25 21:36:27 sv-db1 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (2): svproddbbackup.blob.core.windows.net
Jul 25 21:36:27 sv-db1 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (3): svproddbbackup.blob.core.windows.net
Jul 25 21:36:27 sv-db1 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (4): svproddbbackup.blob.core.windows.net
Jul 25 21:36:28 sv-db1 wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling#012        DETAIL: Traceback (most recent call last):#012          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 578, in main#012            pool_size=args.pool_size)#012          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 197, in database_backup#012            **kwargs)#012          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 502, in _upload_pg_cluster_dir#012            pool.put(tpart)#012          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload_pool.py", line 108, in put#012            self._wait()#012          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload_pool.py", line 65, in _wait#012            raise val#012        error: (4, 'Interrupted system call')#012        #012        STRUCTURED: time=2016-07-26T01:36:28.635565-00 pid=20812
```

The interrupted system call is 4 which seems to indicate a timeout has occurred?

**Comment by fdr** [comment]
The error message could afford to be improved, but to retry is at least the right behavior. Does it ever succeed?

**Comment by bmleshopventory** [comment]
It actually does not succeed. We actually hadn't had a backup complete in about 10 days without realizing it and we triggered a backup every night. I switched to the S3 integration and that seems to be going smoothly.

**Comment by fdr** [comment]
Are you hosting in Azure? I am wondering if your link to WABS was slow enough somehow that it caused timeouts.

**Comment by bmleshopventory** [comment]
Hosted in digital ocean and they don't have an equivalent service so we have to go outside.

**Comment by smartb-pair** [comment]
We are seeing this very often backing up to S3. Is there a way to get more detailed information about the nature of the failure?

**Comment by fdr** [comment]
I don't have any specific advice on the matter, no.
