### ISSUE TITLE
WAL-E on Ubuntu 14.04 w/ Apparmor..

### ISSUE THREAD

**Issue by diranged** [wal-e/wal-e#270]
Hey we just ran into this issue -- I havn't had enough time to dig into it in depth, but I wanted to check if it was a known issue. We were pulling down a copy of the database when suddenly we started getting an uncontrollable stream of these errors:

```
        STRUCTURED: time=2016-08-17T23:45:32.746015-00 pid=8793
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000031.tar.lzo.
        HINT: The absolute S3 key is staging-wal-logs/staging-eu1/atlas/basebackups_005/base_00000002000000DA00000069_00000040/tar_partitions/part_00000031.tar.lzo.
        STRUCTURED: time=2016-08-17T23:45:32.746437-00 pid=8793
lzop: Inappropriate ioctl for device: <stdin>
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3/s3_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/tar_partition.py", line 278, in tarfile_extract
            cat_extract(tar, member, relpath)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/tar_partition.py", line 215, in cat_extract
            with pipeline.get_cat_pipeline(pipeline.PIPE, dest.f) as pl:
          File "/usr/local/lib/python2.7/dist-packages/wal_e/pipeline.py", line 92, in __enter__
            self.stdin = pipebuf.NonBlockBufferedWriter(stdin)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/pipebuf.py", line 225, in __init__
            _setup_fd(self._fd)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/pipebuf.py", line 62, in _setup_fd
            set_buf_size(fd)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/pipebuf.py", line 53, in set_buf_size
            fcntl.fcntl(fd, fcntl.F_SETPIPE_SZ, OS_PIPE_SZ)
        IOError: [Errno 1] Operation not permitted
        
        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2016-08-17T23:45:34.534462-00 pid=8793
lzop: Inappropriate ioctl for device: <stdin>
lzop: Inappropriate ioctl for device: <stdin>
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
```

We are pretty sure this is Apparmor related.. thoughts?

**Comment by diranged** [comment]
I should add that this was with wal-e 0.8.1. I'll try a newer version of wal-e later tonight

**Comment by diranged** [comment]
So I've tried with both 0.9.x and 0.8x releases of Wal-E and I run into the same issue. I've tried on both the 3.13 and 4.4 kernels as well. I am trying now to boot a host without apparmor installed at all just to 100% confirm that its an apparmor issue.

**Comment by diranged** [comment]
I've updated the title now that I have tracked down the bug. Wal-e writes out a ton of data to big large pipes. The linux kernel recently limited the default size of these pipes: https://gitlab.com/ebenard/linux-stable/commit/759c01142a5d0f364a462346168a56de28a80f52

`echo 0 > /proc/sys/fs/pipe-user-pages-soft` fixes the issue.

**Comment by fdr** [comment]
Heh. I would rather not oblige people to mess with their kernel to make WAL-E work. I did do the large-pipes thing for efficiency reasons, by reducing syscalls.

WAL-E reads `/proc/sys/fs/pipe-max-size` to figure out how to set the pipe size. Can you perhaps suggest a better algorithm that adaptively works within the user's limit?

**Comment by tmc** [comment]
FWIW this is still an issue.

**Comment by kamalmarhubi** [comment]
As @tmc says, this is still an issue.

> WAL-E reads `/proc/sys/fs/pipe-max-size` to figure out how to set the pipe size.

Specifically, there is no reason to expect [the fcntl call to set pipe size](https://github.com/wal-e/wal-e/blob/cdfaa92698ba19bbbff23ab2421fb377f9affb60/wal_e/pipebuf.py#L53) to succeed. The `/proc/sys/fs/pipe-max-size` is the max size you can expect *might* succeed, but as pointed out by earlier comments, there are a variety of reasons it may fail: per-user and per-process limits may be in effect.

>  Can you perhaps suggest a better algorithm that adaptively works within the user's limit?

A simple algorithm would be to try the max size, and repeatedly divide by two until it succeeds. An even simpler thing is to just catch the failure and log a warning with the actual pipe size saying performance might be poor.

I'm pretty sure we all agree that having no backups running because an optimization couldn't be applied is not the right situation. This bit us: an earlier failed base backup left a running wal-e process doing nothing, but still holding onto the some large pipes. I believe this made the per-user pipe pages limit kick in, and so the scheduled base backup kept failing because of the fcntl raised EPERM.

@fdr if you have a preference on how to solve this, I would be happy to contribute a fix.

**Comment by lachesis** [comment]
Just to help anyone Googling for the error message (like me):
```
wal_e.main   ERROR    MSG: could not run one or more external programs WAL-E depends upon
        DETAIL: Could not run the following programs, are they installed? psql
        STRUCTURED: time=2017-07-07T03:00:01.957961-00 pid=25833
```

I had to edit the Python and add a call to `traceback` to print the actual exception to find this issue. The error message presented when this happens is quite misleading and led me to lots of people trying to figure out $PATH.

**Comment by fdr** [comment]
> As @tmc says, this is still an issue.
> 
> > WAL-E reads `/proc/sys/fs/pipe-max-size` to figure out how to set the pipe size.
> 
> Specifically, there is no reason to expect [the fcntl call to set pipe size](https://github.com/wal-e/wal-e/blob/cdfaa92698ba19bbbff23ab2421fb377f9affb60/wal_e/pipebuf.py#L53) to succeed. The `/proc/sys/fs/pipe-max-size` is the max size you can expect _might_ succeed, but as pointed out by earlier comments, there are a variety of reasons it may fail: per-user and per-process limits may be in effect.
> 
> > Can you perhaps suggest a better algorithm that adaptively works within the user's limit?
> 
> A simple algorithm would be to try the max size, and repeatedly divide by two until it succeeds. An even simpler thing is to just catch the failure and log a warning with the actual pipe size saying performance might be poor.
> 
> I'm pretty sure we all agree that having no backups running because an optimization couldn't be applied is not the right situation. This bit us: an earlier failed base backup left a running wal-e process doing nothing, but still holding onto the some large pipes. I believe this made the per-user pipe pages limit kick in, and so the scheduled base backup kept failing because of the fcntl raised EPERM.
> 
> @fdr if you have a preference on how to solve this, I would be happy to contribute a fix.

Sure, that algorithm sounds great. WAL-E is not so much a moving target these days, so you could account for how many pipes WAL-E generates today and rather efficiently figure out how big to make the buffers. Though, really, this puts whoever is committing to WAL-E today on the hook, so my say so doesn't mean much. To be honest, I haven't taken care of WAL-E much since I've had children. I use it, it works great for me, and WAL-G seems to work great for other people and I'd probably work on that in the future; the elimination of memory copies is just the next major step in making things faster and simpler. WAL-E evolved in 2011, when the software landscape was very different.
