### ISSUE TITLE
TypeError: memoryview: str object does not have the buffer interface on centos 6 with python 3.4

### ISSUE THREAD

**Issue by preperat** [wal-e/wal-e#282]
We are trying to run wal-e 1.0.0 on centos 6 with python 3.4 talking to rackspace cloudfiles via swift.
It runs fine for us on ubuntu 14.04, but the following command gives us a nasty looking stack trace (also below):

```
WALE_SWIFT_PREFIX='swift://pgBackup' SWIFT_AUTHURL='https://identity.api.rackspacecloud.com/v2.0/' SWIFT_REGION='SYD' SWIFT_TENANT='xxxx' SWIFT_USER='xxx' SWIFT_PASSWORD='xxxx' /opt/wale/bin/wal-e backup-push /var/lib/pgsql/9.5/data```

Stack trace:

wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2016-10-12T23:43:01.550130-00 pid=24457
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to swift://pgBackup/basebackups_005/base_00000001000000020000000C_00000040/extended_version.txt.
        STRUCTURED: time=2016-10-12T23:43:02.066770-00 pid=24457
requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): identity.api.rackspacecloud.com
requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): storage101.syd2.clouddrive.com
wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2016-10-12T23:43:06.180901-00 pid=24457
NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/lib64/python3.4/http/client.py", line 929, in send
            self.sock.sendall(data)
          File "/opt/wale/lib/python3.4/site-packages/gevent/_ssl3.py", line 378, in sendall
            return socket.sendall(self, data, flags)
          File "/opt/wale/lib/python3.4/site-packages/gevent/_socket3.py", line 385, in sendall
            data_memory = _get_memory(data)
          File "/opt/wale/lib/python3.4/site-packages/gevent/_socket3.py", line 29, in _get_memory
            mv = memoryview(data)
        TypeError: memoryview: str object does not have the buffer interface

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/opt/wale/lib/python3.4/site-packages/wal_e/cmd.py", line 603, in main
            pool_size=args.pool_size)
          File "/opt/wale/lib/python3.4/site-packages/wal_e/operator/backup.py", line 197, in database_backup
            **kwargs)
          File "/opt/wale/lib/python3.4/site-packages/wal_e/operator/backup.py", line 487, in _upload_pg_cluster_dir
            content_type='text/plain')
          File "/opt/wale/lib/python3.4/site-packages/wal_e/worker/worker_util.py", line 13, in uri_put_file
            content_type=content_type)
          File "/opt/wale/lib/python3.4/site-packages/wal_e/blobstore/swift/utils.py", line 37, in uri_put_file
            container_name, url_tup.path, fp, content_type=content_type
          File "/opt/wale/lib/python3.4/site-packages/swiftclient/client.py", line 1796, in put_object
            response_dict=response_dict)
          File "/opt/wale/lib/python3.4/site-packages/swiftclient/client.py", line 1647, in _retry
            service_token=self.service_token, **kwargs)
          File "/opt/wale/lib/python3.4/site-packages/swiftclient/client.py", line 1278, in put_object
            conn.putrequest(path, headers=headers, data=data)
          File "/opt/wale/lib/python3.4/site-packages/swiftclient/client.py", line 447, in putrequest
            return self.request('PUT', full_path, data, headers, files)
          File "/opt/wale/lib/python3.4/site-packages/swiftclient/client.py", line 437, in request
            files=files, **self.requests_args)
          File "/opt/wale/lib/python3.4/site-packages/swiftclient/client.py", line 420, in _request
            return self.request_session.request(*arg, **kwarg)
          File "/opt/wale/lib/python3.4/site-packages/requests/sessions.py", line 475, in request
            resp = self.send(prep, **send_kwargs)
          File "/opt/wale/lib/python3.4/site-packages/requests/sessions.py", line 596, in send
            r = adapter.send(request, **kwargs)
          File "/opt/wale/lib/python3.4/site-packages/requests/adapters.py", line 446, in send
            low_conn.send(i)
          File "/usr/lib64/python3.4/http/client.py", line 933, in send
            self.sock.sendall(d)
          File "/opt/wale/lib/python3.4/site-packages/gevent/_ssl3.py", line 378, in sendall
            return socket.sendall(self, data, flags)
          File "/opt/wale/lib/python3.4/site-packages/gevent/_socket3.py", line 385, in sendall
            data_memory = _get_memory(data)
          File "/opt/wale/lib/python3.4/site-packages/gevent/_socket3.py", line 29, in _get_memory
            mv = memoryview(data)
        TypeError: memoryview: str object does not have the buffer interface

        STRUCTURED: time=2016-10-12T23:43:07.266486-00 pid=24457
```

We've checked our credentials in this environment as a backup-list command runs fine.

For reference pip3 freeze gives:

```
bash-4.1$ /opt/wale/bin/pip3
pip3    pip3.4
bash-4.1$ /opt/wale/bin/pip3
pip3    pip3.4
bash-4.1$ /opt/wale/bin/pip3 freeze
Babel==2.3.4
debtcollector==1.8.0
envdir==0.7
futures==3.0.5
gevent==1.1.2
greenlet==0.4.10
iso8601==0.1.11
keystoneauth1==2.13.0
monotonic==1.2
msgpack-python==0.4.8
netaddr==0.7.18
netifaces==0.10.5
oslo.config==3.17.0
oslo.i18n==3.9.0
oslo.serialization==2.13.0
oslo.utils==3.16.0
pbr==1.10.0
positional==1.1.1
pyparsing==2.1.10
python-keystoneclient==3.6.0
python-swiftclient==3.1.0
pytz==2016.7
requests==2.11.1
rfc3986==0.4.1
six==1.10.0
stevedore==1.17.1
wal-e==1.0.0
wrapt==1.10.8
```

**Comment by fdr** [comment]
It's probable that Swift is broken in 1.0. Would you like to have a go at fixing it by peppering `.encode('utf-8')` in the source?

**Comment by joehealy** [comment]
We can try that

**Comment by fdr** [comment]
If you are ambitious you could try to get a blackbox test going (see `./tests/test_blackbox.py`) so wal-e won't support simple regressions in the future. But I'll take a spot-fix over nothing for sure.

**Comment by joehealy** [comment]
I have made it "work" by adding a data.encode("utf8") inside of _get_memory(data) in /opt/wale/lib/python3.4/site-packages/gevent/_socket3.py

Not entirely sure that I am happy with this as a fix though...

Looking up at our stacktrace, it seems that everything comes from within /opt/wale except for the call within 
/usr/lib64/python3.4/http/client.py. I wonder if that could be a cause or a symptom.

**Comment by fdr** [comment]
You probably want to do something with either the body of or call sites of `uri_put_file` to encode unicode as necessary.

**Comment by joehealy** [comment]
Made a fix - PR coming. Needed to send the version string and the sentinel through as BytesIO objects rather than StringIO objects.

**Comment by joehealy** [comment]
Sent https://github.com/wal-e/wal-e/pull/288 Though I am not sure how best to test that all data is sent as bytes rather than a string and so supports the memoryview inteface.

**Comment by fdr** [comment]
@joehealy does that PR fix all you known problems? I'll release it soon if so.

**Comment by fdr** [comment]
Fixed by #288

**Comment by joehealy** [comment]
Just confirming, this fixes all our known problems.

**Comment by omctim** [comment]
I am testing the restore function at present, so far its looking good. 

Backup is working as expected.

**Comment by fdr** [comment]
Awesome! Grab the new release :)
