### ISSUE TITLE
wal-e fails while deleting files in WABS

### ISSUE THREAD

**Issue by perfectayush** [wal-e/wal-e#293]
While deleting old backups using wal-e delete --retain 4 we are encountering following exception for missing resources which results in infinite retries:
```
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/opt/wal-e/lib/python3.4/site-packages/azure/storage/storageclient.py", line 171, in _perform_request
            resp = self._filter(request)
          File "/opt/wal-e/lib/python3.4/site-packages/azure/storage/storageclient.py", line 160, in _perform_request_worker
            return self._httpclient.perform_request(request)
          File "/opt/wal-e/lib/python3.4/site-packages/azure/storage/_http/httpclient.py", line 223, in perform_request
            raise HTTPError(status, message, respheaders, respbody)
        azure.storage._http.HTTPError: The specified resource does not exist.
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/worker/wabs/wabs_deleter.py", line 17, in _delete_batch
            self.wabs_conn.delete_blob(self.container, blob.name)
          File "/opt/wal-e/lib/python3.4/site-packages/azure/storage/blob/blobservice.py", line 2323, in delete_blob
            self._perform_request(request)
          File "/opt/wal-e/lib/python3.4/site-packages/azure/storage/storageclient.py", line 178, in _perform_request
            _storage_error_handler(ex)
          File "/opt/wal-e/lib/python3.4/site-packages/azure/storage/_serialization.py", line 25, in _storage_error_handler
            return _general_error_handler(http_error)
          File "/opt/wal-e/lib/python3.4/site-packages/azure/storage/_common_error.py", line 82, in _general_error_handler
            raise AzureHttpError(message, http_error.status)
        azure.common.AzureMissingResourceHttpError: The specified resource does not exist.
        <?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
        RequestId:f08ef006-0001-010b-17dd-354f3c000000
        Time:2016-11-03T14:22:49.8694249Z</Message></Error>
        
        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2016-11-03T14:22:49.706615-00 pid=28474
```

I am not exactly sure why the resources are missing and what it means. But having an infinite retry for the resource that's not there doesn't make sense. I have a patch to fix this, but I am not sure why exactly are we missing the resources. Is it of importance, missing these resources.

Also, I want to add that earlier wal-e were using some other container for the wal-e backups. We recently changed it without moving old files to the new container. Does that affect the wal-e somehow with respect to this and is it trying to delete resources from the old container? There should be a way to reset state with respect to this.

Full log:
[error_log.txt](https://github.com/wal-e/wal-e/files/569252/error_log.txt)

**Comment by perfectayush** [comment]
@fdr regarding https://github.com/wal-e/wal-e/pull/294 which I submitted as fix for infinite retries, I finally figured it out why it was happening. The sas key that I was using for running the delete command didn't had delete permission. But instead of giving unauthorized error (HTTP 401), Azure WABS throws HTTP 404 Resource Missing. I think we should update the exception log message to also add a message warning  that SAS key may not have permission to delete resource. We should add it in the docs as well.

**Comment by fdr** [comment]
On Thu, Dec 1, 2016 at 2:02 AM Ayush Goyal <notifications@github.com> wrote:

> @fdr <https://github.com/fdr> regarding #294
> <https://github.com/wal-e/wal-e/pull/294> which I submitted as fix for
> infinite retries, I finally figured it out why it was happening. The sas
> key that I was using for running the delete command didn't had delete
> permission. But instead of giving unauthorized error (HTTP 401), Azure WABS
> throws HTTP 404 Resource Missing. I think we should update the exception
> log message to also add a message warning that SAS key may not have
> permission to delete resource. We should add it in the docs as well.
>

Sure, would you kindly submit a patch and adjustments to catch more
exception types, please?

**Comment by perfectayush** [comment]
@fdr I have discussed this with my team, and we think that instead of logging AzureMissingResourceHttpError exception as warning we should exit wale, since this is a delete operation, we might be passing wrong parameters(wrong container maybe) or wrong sas key as in case stated above. In either case it's better to fail the process, rather than logging silently. I am not familiar with gevent, can you tell me if a simple sys.exit will work in this case or do I need to do more handling. I will submit a patch for exiting if you think this is the right way to handle this.

**Comment by fdr** [comment]
Sure. You can raise a "UserException". That's how all other
nicely-formatted exits are handled.
