### ISSUE TITLE
Doesn't work on CentOS 7

### ISSUE THREAD

**Issue by earsdown** [wal-e/wal-e#295]
Started looking to upgrade to wal-e 1.x to CentOS 7, and I'm getting this error:

```
[root@localhost package]# pip install --upgrade  wal-e
You are using pip version 7.1.0, however version 9.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting wal-e
  Using cached wal-e-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/usr/local/src/pip-build-MkNRJY/wal-e/setup.py", line 19, in <module>
        raise RuntimeError('Python versions < 3.4 are not supported.')
    RuntimeError: Python versions < 3.4 are not supported.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /usr/local/src/pip-build-MkNRJY/wal-e
```

So... uhm... is there like, a dramatic, earth-shattering, life-ending reason why wal-e can't possibly continue to work on python 2?

I don't think maintaining compatibility with the most popular enterprise linux distribution on the planet is too much to ask.

**Comment by david-richer-adsk** [comment]
Same issue here, we would like to upgrade to latest version 1.0 but we are using CentOS 6 with python 2.6...

**Comment by snerdish** [comment]
Whoops, yes, this is kind of a deal-breaker.

**Comment by PChambino** [comment]
I have the same issue on Ubuntu 16.04. I am having a difficult time figuring out what is the best approach to run wal-e under Python 3. I do have Python 3 installed, however I also have Python 2 installed and `python` defaults to version 2. According to [PEP 394] it is not recommended to default  `python` to version 3 system-wide.

So what is the best approach? Some easy to follow steps would help. According to [PEP 394] the shebang lines should reference `python3`, not `python`. Would this help?

[PEP 394]: https://www.python.org/dev/peps/pep-0394/

**Comment by PChambino** [comment]
@fdr I believe you led the python 2 -> 3 change, so I would like to know what you think about the above comment. Keep in mind that not everyone that uses wal-e is a python expert. (I am not a python expert. 😛 )

**Comment by fdr** [comment]
You can continue to use wal-e 0.9.x. I think this will be fine for a couple of years.

**Comment by earsdown** [comment]
@fdr I think a better approach would be to continue to support both versions of python for the time being. Critical patches and bugfixes aren't getting backported to 0.9.x, which basically means 0.9.x appears to be dead. There doesn't seem to any good reason to drop support for python 2 this soon.

**Comment by fdr** [comment]
On Mon, Nov 21, 2016 at 2:45 PM earsdown <notifications@github.com> wrote:

> @fdr <https://github.com/fdr> I think a better approach would be to
> continue to support both versions of python for the time being. Critical
> patches and bugfixes aren't getting backported to 0.9.x, which basically
> means 0.9.x appears to be dead. There doesn't seem to any good reason to
> drop support for python 2 this soon.
>
Well, maybe. It's not that simple. Maybe patches welcome, depending on how
invasive it is.

Consider some anecdote: years ago I had to backport  a Python 3.2-ish
version of subprocess.py to attain a fix for a file descriptor leak years
ago. I reported the bug to Python 2, and was told that the project was dead
and there would be no backport outside a security issue. Sometime later, I
was forced to drop Python 2.6 support rather suddenly because the Azure
library did so. If I did more research, I can probably come up with more
problems. All in all, I felt that considering the:

* Limited maintenance budget of WAL-E (i.e. my copious free time once in a
while and a smattering of bug reports and I only am invested in one
platform)
* Its stability: major changes haven't happened in quite some time, v0.9 is
fine and if there are backport requests I can take them
* Momentum of bit-rot issues

That I would try to cut the supported versions of Python, rather than more
than doubling them (by crossing the 2 vs 3 divide *and* handling 2.7 and
3.4 and 3.5).

So that was my reasoning. If we need to find a backporting method, we can.
But I assess that WAL-E change is so slow now-a-years that by the time 0.9
ages into obsolescence there will be fewer issues.

For what it's worth, I use WAL-E on Amazon Linux, which is kind-of CentOS6
like and, yes, I install a python3 and run pip-3.4 (now pip-3.5) and it
works well.

**Comment by PChambino** [comment]
@fdr Thanks for your reply and for your work on wal-e. 😃  Your short description of how you install wal-e with python3 enabled me to correctly install wal-e on Ubuntu 16.04.

```sh
sudo apt-get install python3-pip
sudo pip3 install wal-e[PROVIDER]
```

On Ubuntu 14.04 I got inconsistent behaviour, for some reason sometimes I would not get a `pip3` binary, but it is possible to install wal-e using python3 with this command:

```sh
sudo python3 -m pip install wal-e[PROVIDER]
```

I agree that is easier to maintain compatibility with only one major Python version and I support your decision. However, since not everyone that uses wal-e knows its way around the Python ecosystem and to avoid these kind of issues,

1. what do you think about adding a notice pointing people to the 0.9.x version if they want to continue using python2?
2. also, what do you think of having a community maintained wiki page with instructions of how to install wal-e 1.0.x on major distributions?

**Comment by fdr** [comment]
@PChambino sorry for the long delay.

I don't mind there being more references, would you (or some other onlooking volunteer?) be willing to work on that? I think perhaps some hyperlinks and checked in `.rst` files (like `README`) might suffice.

A primary problem for WAL-E as a project has been maintaining the amount of surface area at an acceptable level relative to the maintenance it gets.

**Comment by tvarsis** [comment]
> sudo python3 -m pip install wal-e
It should really be an "Installation" part in the documentation where this should be included. Spent 3 days trying to get it to work with pyhon3 on Ubuntu 14.04. And when I did the above, it worked directly. I'm not sure if anything else is needed, since I did a lot of stuff, but I think this was the key for getting it to work. Anyway, thanks for a really great tool!

**Comment by fdr** [comment]
That's a nice portable solution, I agree. I'll add it to the README as you suggest.

**Comment by fdr** [comment]
I did that. Seem good?

**Comment by tvarsis** [comment]
@fdr Yeah, great! I have done a pull request with some more updates to the readme. Might do one more once I have completed the installation on more systems. Thanks!
