### ISSUE TITLE
Utilize RA-GRS Blob Storage in Azure

### ISSUE THREAD

**Issue by lentferj** [wal-e/wal-e#300]
I am looking for a way to utilize the Read-Acess Geo-Redundant Blob-Storage in Azure with wal-e. This would provide a way of setting up a wal-shipping secondary in another Azure DC.
I have setup wal-e as far as being able to make basebackups and archive WAL files to a RA-GRS storage account. Also I can restore the backup within in the same DC.
I can't figure out how setup wal-e to access the blob storage in the 2nd Azure DC. If I use the same options as in the 1st DC I get this (already elsewhere documented) error:

lzop: <stdin>: not a lzop file

As far as I understood, it is necessary to us a secondary endpoint to correctly access the read-only part of the RA-GRS blob account in azure (e.g. "storage-account"-secondary.blob.core.windows.net instead of "storage-account".blob.core.windows.net).
I can't find a way to tell this to wal-e, adding "-secondary" to either the "-a" option or the --wabs-prefix or to both doesn't succeed. Any hints on this or is this something that would need to be implemented?

**Comment by lentferj** [comment]
I am actually not too sure anymore it is a problem with the secondary endpoint, as I can restore single WAL files without any problem in the 2nd DC. But when trying to to backup-fetch I get:
`
-bash-4.2$ WABS_ACCESS_KEY=foobar wal-e -a itbbpghagrs  --wabs-prefix=wabs://itbbpgwal backup-fetch /var/lib/pgsql/9.6/data LATEST
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-fetch".
        STRUCTURED: time=2016-12-05T15:04:06.379225-00 pid=29905
wal_e.worker.wabs.wabs_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000000.tar.lzo.
        HINT: The absolute WABS blob is basebackups_005/base_0000002200000001000000F4_00000096/tar_partitions/part_00000000.tar.lzo.
        STRUCTURED: time=2016-12-05T15:04:08.697090-00 pid=29905
wal_e.worker.wabs.wabs_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000001.tar.lzo.
        HINT: The absolute WABS blob is basebackups_005/base_0000002200000001000000F4_00000096/tar_partitions/part_00000001.tar.lzo.
        STRUCTURED: time=2016-12-05T15:04:08.700824-00 pid=29905
lzop: <stdin>: not a lzop file
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/usr/lib64/python3.4/tarfile.py", line 2260, in next
            tarinfo = self.tarinfo.fromtarfile(self)
          File "/usr/lib64/python3.4/tarfile.py", line 1088, in fromtarfile
            obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
          File "/usr/lib64/python3.4/tarfile.py", line 1024, in frombuf
            raise EmptyHeaderError("empty header")
        tarfile.EmptyHeaderError: empty header

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/usr/lib/python3.4/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/lib/python3.4/site-packages/wal_e/worker/wabs/wabs_worker.py", line 76, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/usr/lib/python3.4/site-packages/wal_e/tar_partition.py", line 267, in tarfile_extract
            bufsize=pipebuf.PIPE_BUF_BYTES)
          File "/usr/lib64/python3.4/tarfile.py", line 1583, in open
            t = cls(name, filemode, stream, **kwargs)
          File "/usr/lib64/python3.4/tarfile.py", line 1475, in __init__
            self.firstmember = self.next()
          File "/usr/lib64/python3.4/tarfile.py", line 2275, in next
            raise ReadError("empty file")
        tarfile.ReadError: empty file

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2016-12-05T15:04:33.293637-00 pid=29905
wal_e.worker.wabs.wabs_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000001.tar.lzo.
        HINT: The absolute WABS blob is basebackups_005/base_0000002200000001000000F4_00000096/tar_partitions/part_00000001.tar.lzo.
        STRUCTURED: time=2016-12-05T15:04:33.397374-00 pid=29905


------ here it hangs and I need to CTRL+C


^CKeyboardInterrupt
Traceback (most recent call last):
  File "/bin/wal-e", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/wal_e/cmd.py", line 576, in main
    pool_size=args.pool_size)
  File "/usr/lib/python3.4/site-packages/wal_e/operator/backup.py", line 156, in database_fetch
    p.join(raise_error=True)
  File "/usr/lib64/python3.4/site-packages/gevent/pool.py", line 520, in join
    self._empty_event.wait(timeout=timeout)
  File "/usr/lib64/python3.4/site-packages/gevent/event.py", line 207, in wait
    return self._wait(timeout)
  File "/usr/lib64/python3.4/site-packages/gevent/event.py", line 117, in _wait
    gotit = self._wait_core(timeout)
  File "/usr/lib64/python3.4/site-packages/gevent/event.py", line 95, in _wait_core
    result = self.hub.switch()
  File "/usr/lib64/python3.4/site-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
KeyboardInterrupt

**Comment by lentferj** [comment]
Shoot me.
I used a very small VM (only 650MB of RAM) for testing and the CentOS image didn't have swap configured either. So the box was just running out of RAM when decompressing the base backup lzo files. Adding 2GB of swap file solved the issue. Sorry for bothering.
