### ISSUE TITLE
lzop: Inappropriate ioctl for device: <stdin>

### ISSUE THREAD

**Issue by dabealu** [wal-e/wal-e#303]
Hello, faced error described below when trying to backup-fetch with WAL-E 1.0.1 installed with pip3. Backup was created using WAL-E 0.8.1 and stored in s3 compatible storage (https://minio.io/), this storage server uses self-signed SSL certificate and we use WALE_S3_ENDPOINT=https+path://<server_fqdn>:9000 variable to point WAL-E to this server.

```
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000232.tar.lzo.
        HINT: The absolute S3 key is path_to_backup/basebackups_005/base_0000000100003175000000DE_00429704/tar_partitions/part_00000232.tar.lzo.
        STRUCTURED: time=2016-12-14T12:34:54.449660-00 pid=21
lzop: Inappropriate ioctl for device: <stdin>
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/usr/local/lib/python3.4/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/s3/s3_worker.py", line 83, in fetch_partition
            raise exc
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/s3_util.py", line 200, in write_and_return_error
            key.get_contents_to_file(stream)
          File "/usr/local/lib/python3.4/dist-packages/boto/s3/key.py", line 1650, in get_contents_to_file
            response_headers=response_headers)
          File "/usr/local/lib/python3.4/dist-packages/boto/s3/key.py", line 1482, in get_file
            query_args=None)
          File "/usr/local/lib/python3.4/dist-packages/boto/s3/key.py", line 1535, in _get_file_internal
            for bytes in self:
          File "/usr/local/lib/python3.4/dist-packages/boto/s3/key.py", line 386, in next
            data = self.resp.read(self.BufferSize)
          File "/usr/local/lib/python3.4/dist-packages/boto/connection.py", line 413, in read
            return http_client.HTTPResponse.read(self, amt)
          File "/usr/lib/python3.4/http/client.py", line 500, in read
            return super(HTTPResponse, self).read(amt)
          File "/usr/lib/python3.4/http/client.py", line 539, in readinto
            n = self.fp.readinto(b)
          File "/usr/lib/python3.4/socket.py", line 371, in readinto
            return self._sock.recv_into(b)
          File "/usr/local/lib/python3.4/dist-packages/gevent/_ssl3.py", line 405, in recv_into
            return self.read(nbytes, buffer)
          File "/usr/local/lib/python3.4/dist-packages/gevent/_ssl3.py", line 238, in read
            self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)
          File "/usr/local/lib/python3.4/dist-packages/gevent/_socket3.py", line 144, in _wait
            self.hub.wait(watcher)
          File "/usr/local/lib/python3.4/dist-packages/gevent/hub.py", line 630, in wait
            result = waiter.get()
          File "/usr/local/lib/python3.4/dist-packages/gevent/hub.py", line 878, in get
            return self.hub.switch()
          File "/usr/local/lib/python3.4/dist-packages/gevent/hub.py", line 609, in switch
            return greenlet.switch(self)
        socket.timeout: The read operation timed out

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2016-12-14T12:35:04.335794-00 pid=21
```

**Comment by dabealu** [comment]
Also, got another error type, during recovery with same circumstances as in previous message except recovering with WAL-E version 0.8.1 (backup was created with this version) and using valid LetsEncrypt certificates on storage server:
```
lzop: Inappropriate ioctl for device: <stdin>
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3/s3_worker.py", line 83, in fetch_partition
            raise exc
        SSLError: ('The read operation timed out',)
        
        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
```

**Comment by dabealu** [comment]
Seem like this issue caused by difference in versions with which backup was created (0.8.1)  and then restored (1.0.1).
Works fine when using same version (0.8.1).
