### ISSUE TITLE
Sometimes wal-e fails to push backup to s3

### ISSUE THREAD

**Issue by CyberDem0n** [wal-e/wal-e#318]
Hi.

Recently I've noticed that sometimes `wal-e --aws-instance-profile backup-push` sometimes fails to push backup to S3 with the following message:

```python
wal_e.worker.upload INFO     MSG: begin uploading a base backup volume
        DETAIL: Uploading to "s3://our-bucket/clustername/wal/basebackups_005/base_00000026000018D80000003E_10935416/tar_partitions/part_00000154.tar.lzo".
        STRUCTURED: time=2017-02-19T13:28:50.695937-00 pid=18726
boto         ERROR    Caught exception reading instance data
        Traceback (most recent call last):
          File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
            h.request(req.get_method(), req.selector, req.data, headers)
          File "/usr/lib/python3.4/http/client.py", line 1125, in request
            self._send_request(method, url, body, headers)
          File "/usr/lib/python3.4/http/client.py", line 1163, in _send_request
            self.endheaders(body)
          File "/usr/lib/python3.4/http/client.py", line 1121, in endheaders
            self._send_output(message_body)
          File "/usr/lib/python3.4/http/client.py", line 951, in _send_output
            self.send(msg)
          File "/usr/lib/python3.4/http/client.py", line 886, in send
            self.connect()
          File "/usr/lib/python3.4/http/client.py", line 863, in connect
            self.timeout, self.source_address)
          File "/usr/local/lib/python3.4/dist-packages/gevent/socket.py", line 99, in create_connection
            raise err # pylint:disable=raising-bad-type
          File "/usr/local/lib/python3.4/dist-packages/gevent/socket.py", line 86, in create_connection
            sock.connect(sa)
          File "/usr/local/lib/python3.4/dist-packages/gevent/_socket3.py", line 306, in connect
            self._wait(self._write_event)
          File "/usr/local/lib/python3.4/dist-packages/gevent/_socket3.py", line 157, in _wait
            self.hub.wait(watcher)
          File "/usr/local/lib/python3.4/dist-packages/gevent/hub.py", line 651, in wait
            result = waiter.get()
          File "/usr/local/lib/python3.4/dist-packages/gevent/hub.py", line 899, in get
            return self.hub.switch()
          File "/usr/local/lib/python3.4/dist-packages/gevent/hub.py", line 630, in switch
            return RawGreenlet.switch(self)
        socket.timeout: timed out
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/local/lib/python3.4/dist-packages/boto/utils.py", line 210, in retry_url
            r = opener.open(req, timeout=timeout)
          File "/usr/lib/python3.4/urllib/request.py", line 463, in open
            response = self._open(req, data)
          File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
            '_open', req)
          File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
            result = func(*args)
          File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
            return self.do_open(http.client.HTTPConnection, req)
          File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
            raise URLError(err)
        urllib.error.URLError: <urlopen error timed out>
boto         ERROR    Unable to read instance data, giving up
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/wal_e/retries.py", line 62, in shim
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/upload.py", line 140, in put_file_helper
    return self.blobstore.uri_put_file(self.creds, url, tf)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/s3_util.py", line 52, in uri_put_file
    k = _uri_to_key(creds, uri, conn=conn)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/s3_util.py", line 36, in _uri_to_key
    conn = cinfo.connect(creds)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/calling_format.py", line 207, in connect
    return connection.S3Connection(**_s3connection_opts_from_uri(impl))
  File "/usr/local/lib/python3.4/dist-packages/boto/s3/connection.py", line 191, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/usr/local/lib/python3.4/dist-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/local/lib/python3.4/dist-packages/boto/auth.py", line 997, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['S3HmacAuthV4Handler'] Check your credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/upload.py", line 145, in __call__
    k = put_file_helper()
  File "/usr/local/lib/python3.4/dist-packages/wal_e/retries.py", line 72, in shim
    exc_processor_cxt=exc_processor_cxt)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/retries.py", line 104, in retry_with_count_internal
    side_effect_func(exc_tup, exc_processor_cxt)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/upload.py", line 135, in log_volume_failures_on_error
    raise typ(value).with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/retries.py", line 62, in shim
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/upload.py", line 140, in put_file_helper
    return self.blobstore.uri_put_file(self.creds, url, tf)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/s3_util.py", line 52, in uri_put_file
    k = _uri_to_key(creds, uri, conn=conn)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/s3_util.py", line 36, in _uri_to_key
    conn = cinfo.connect(creds)
  File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/calling_format.py", line 207, in connect
    return connection.S3Connection(**_s3connection_opts_from_uri(impl))
  File "/usr/local/lib/python3.4/dist-packages/boto/s3/connection.py", line 191, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/usr/local/lib/python3.4/dist-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/local/lib/python3.4/dist-packages/boto/auth.py", line 997, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['S3HmacAuthV4Handler'] Check your credentials
Sun Feb 19 13:28:52 2017 <Greenlet at 0x7fc7b826b3d8: <wal_e.worker.upload.PartitionUploader object at 0x7fc7b82bae80>([ExtendedTarInfo(submitted_path='/home/postgres/pg)> failed with NoAuthHandlerFound

wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2017-02-19T13:28:52.151230-00 pid=18726
wal_e.worker.upload INFO     MSG: begin uploading a base backup volume
        DETAIL: Uploading to "s3://our-bucket/clustername/wal/basebackups_005/base_00000026000018D80000003E_10935416/tar_partitions/part_00000155.tar.lzo".
        STRUCTURED: time=2017-02-19T13:28:53.237277-00 pid=18726
NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python3.4/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/upload.py", line 140, in put_file_helper
            return self.blobstore.uri_put_file(self.creds, url, tf)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/s3_util.py", line 52, in uri_put_file
            k = _uri_to_key(creds, uri, conn=conn)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/s3_util.py", line 36, in _uri_to_key
            conn = cinfo.connect(creds)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/calling_format.py", line 207, in connect
            return connection.S3Connection(**_s3connection_opts_from_uri(impl))
          File "/usr/local/lib/python3.4/dist-packages/boto/s3/connection.py", line 191, in __init__
            validate_certs=validate_certs, profile_name=profile_name)
          File "/usr/local/lib/python3.4/dist-packages/boto/connection.py", line 569, in __init__
            host, config, self.provider, self._required_auth_capability())
          File "/usr/local/lib/python3.4/dist-packages/boto/auth.py", line 997, in get_auth_handler
            'Check your credentials' % (len(names), str(names)))
        boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['S3HmacAuthV4Handler'] Check your credentials
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/local/lib/python3.4/dist-packages/wal_e/cmd.py", line 627, in main
            pool_size=args.pool_size)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/operator/backup.py", line 197, in database_backup
            **kwargs)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/operator/backup.py", line 500, in _upload_pg_cluster_dir
            pool.put(tpart)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/upload_pool.py", line 108, in put
            self._wait()
          File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/upload_pool.py", line 65, in _wait
            raise val
          File "/usr/local/lib/python3.4/dist-packages/gevent/greenlet.py", line 536, in run
            result = self._run(*self.args, **self.kwargs)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/upload.py", line 145, in __call__
            k = put_file_helper()
          File "/usr/local/lib/python3.4/dist-packages/wal_e/retries.py", line 72, in shim
            exc_processor_cxt=exc_processor_cxt)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/retries.py", line 104, in retry_with_count_internal
            side_effect_func(exc_tup, exc_processor_cxt)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/upload.py", line 135, in log_volume_failures_on_error
            raise typ(value).with_traceback(tb)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/upload.py", line 140, in put_file_helper
            return self.blobstore.uri_put_file(self.creds, url, tf)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/s3_util.py", line 52, in uri_put_file
            k = _uri_to_key(creds, uri, conn=conn)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/s3_util.py", line 36, in _uri_to_key
            conn = cinfo.connect(creds)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/calling_format.py", line 207, in connect
            return connection.S3Connection(**_s3connection_opts_from_uri(impl))
          File "/usr/local/lib/python3.4/dist-packages/boto/s3/connection.py", line 191, in __init__
            validate_certs=validate_certs, profile_name=profile_name)
          File "/usr/local/lib/python3.4/dist-packages/boto/connection.py", line 569, in __init__
            host, config, self.provider, self._required_auth_capability())
          File "/usr/local/lib/python3.4/dist-packages/boto/auth.py", line 997, in get_auth_handler
            'Check your credentials' % (len(names), str(names)))
        boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['S3HmacAuthV4Handler'] Check your credentials
        
        STRUCTURED: time=2017-02-19T13:28:59.724742-00 pid=18726
```

From this trace I've figured out that boto failed to get credentials from instance metadata and gave up.
As a temporary solution I've changed amount of retries from 10 to 100 in the `/usr/local/lib/python3.4/dist-packages/boto/utils.py` and it helped. Now I wonder, shouldn't wal-e handle such kind of exception as well or it simply should rely on boto?

**Comment by fdr** [comment]
What do you think? Ultimately taking forever to get credentials is a problem, so perhaps some timely termination is a good idea. On the other hand, it's fragile and ugly right now.

**Comment by CyberDem0n** [comment]
Obviously it was only our issue and it was related to the failing EC2 Instance.
