### ISSUE TITLE
wal-e backup-fetch hangs after several segments - s3

### ISSUE THREAD

**Issue by si-rob** [wal-e/wal-e#323]
I'm trying to restore a backup with backup-fetch using an S3 compatible store,  Wal-e lists out several segments and then just sits there indefinitely. 
Wal-e version 1.0.3
Postgres 9.4
Don't really have any other output at this time.

**Comment by si-rob** [comment]
I AM seeing the following, The output from WAL-E does seem to indicate it downloads parts
part_00000001-11 ok..
This was tested with python3.6 but can confirm on 3.5.3 also.

wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000000.tar.lzo.
        HINT: The absolute S3 key is basebackups_005/base_000000020000A1AB00000044_00015136/tar_partitions/part_00000000.tar.lzo.
        STRUCTURED: time=2017-03-13T21:30:48.820961-00 pid=4693
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/usr/local/lib/python3.6/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.6/site-packages/wal_e/worker/s3/s3_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/usr/local/lib/python3.6/site-packages/wal_e/tar_partition.py", line 286, in tarfile_extract
            tar.extract(member, path=dest_path)
          File "/usr/local/lib/python3.6/tarfile.py", line 2045, in extract
            numeric_owner=numeric_owner)
          File "/usr/local/lib/python3.6/tarfile.py", line 2115, in _extract_member
            self.makefile(tarinfo, targetpath)
          File "/usr/local/lib/python3.6/tarfile.py", line 2154, in makefile
            source.seek(tarinfo.offset_data)
          File "/usr/local/lib/python3.6/tarfile.py", line 517, in seek
            raise StreamError("seeking backwards is not allowed")
        tarfile.StreamError: seeking backwards is not allowed

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2017-03-13T21:30:57.764139-00 pid=4693

**Comment by wizzat** [comment]
@si-rob: how did you get this resolved?

**Comment by cyberdelia** [comment]
It looks like a bug in python, see: https://bugs.python.org/issue12800
