### ISSUE TITLE
Error while 

### ISSUE THREAD

**Issue by josemazo** [wal-e/wal-e#330]
Hi! I'm using WAL-E (it's awesome because is just the right tool we need) and I'm getting the next error while fetching a backup from S3:

```
lzop: Inappropriate ioctl for device: <stdin>
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/usr/local/lib/python3.5/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/worker/s3/s3_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/tar_partition.py", line 284, in tarfile_extract
            cat_extract(tar, member, relpath)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/tar_partition.py", line 219, in cat_extract
            copyfileobj.copyfileobj(fp, pl.stdin)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/copyfileobj.py", line 15, in copyfileobj
            shutil.copyfileobj(src, dst, BUFSIZE)
          File "/usr/lib/python3.5/shutil.py", line 73, in copyfileobj
            buf = fsrc.read(length)
          File "/usr/lib/python3.5/tarfile.py", line 698, in readinto
            buf = self.read(len(b))
          File "/usr/lib/python3.5/tarfile.py", line 689, in read
            raise ReadError("unexpected end of data")
        tarfile.ReadError: unexpected end of data

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
```

My installation is:
- ubuntu_x64==16.04
- python==3.5.2
- appdirs==1.4.3
- boto==2.46.1
- gevent==1.2.1
- greenlet==0.4.12
- packaging==16.8
- pyparsing==2.2.0
- six==1.10.0
- wal-e==1.0.3

Maybe some of these are wrong :persevere:

**Comment by tschwaerzl** [comment]
This one was before #333, but maybe one could close this as duplicate?

**Comment by josemazo** [comment]
Yep, Thanks @tschwaerzl.
