### ISSUE TITLE
Error during backup-fetch: lzop: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by matthewoldham** [wal-e/wal-e#333]
Running a wal-e backup fetch using **v1.0.3** on hostB from a backup taken on hostA using the *same* version of wal-e (**v1.0.3**).  Receiving multiple `lzop: Inappropriate ioctl for device` errors in the process:

```
        STRUCTURED: time=2017-05-22T17:15:05.577178-00 pid=24911
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000024.tar.lzo.
        HINT: The absolute S3 key is postgres/wal-e/basebackups_005/base_0000000100000819000000B0_00000032/tar_partitions/part_00000024.tar.lzo.
        STRUCTURED: time=2017-05-22T17:17:34.694509-00 pid=24911
lzop: Inappropriate ioctl for device: <stdin>
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/usr/local/lib/python3.4/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.4/site-packages/wal_e/worker/s3/s3_worker.py", line 83, in fetch_partition
            raise exc
          File "/usr/local/lib/python3.4/site-packages/wal_e/blobstore/s3/s3_util.py", line 200, in write_and_return_error
            key.get_contents_to_file(stream)
          File "/usr/local/lib/python3.4/site-packages/boto/s3/key.py", line 1650, in get_contents_to_file
            response_headers=response_headers)
          File "/usr/local/lib/python3.4/site-packages/boto/s3/key.py", line 1482, in get_file
            query_args=None)
          File "/usr/local/lib/python3.4/site-packages/boto/s3/key.py", line 1535, in _get_file_internal
            for bytes in self:
          File "/usr/local/lib/python3.4/site-packages/boto/s3/key.py", line 386, in next
            data = self.resp.read(self.BufferSize)
          File "/usr/local/lib/python3.4/site-packages/boto/connection.py", line 413, in read
            return http_client.HTTPResponse.read(self, amt)
          File "/usr/lib64/python3.4/http/client.py", line 529, in read
            return super(HTTPResponse, self).read(amt)
          File "/usr/lib64/python3.4/http/client.py", line 568, in readinto
            n = self.fp.readinto(b)
          File "/usr/lib64/python3.4/socket.py", line 374, in readinto
            return self._sock.recv_into(b)
          File "/usr/local/lib64/python3.4/site-packages/gevent/_ssl3.py", line 473, in recv_into
            return self.read(nbytes, buffer)
          File "/usr/local/lib64/python3.4/site-packages/gevent/_ssl3.py", line 295, in read
            self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)
          File "/usr/local/lib64/python3.4/site-packages/gevent/_socket3.py", line 157, in _wait
            self.hub.wait(watcher)
          File "/usr/local/lib64/python3.4/site-packages/gevent/hub.py", line 651, in wait
            result = waiter.get()
          File "/usr/local/lib64/python3.4/site-packages/gevent/hub.py", line 899, in get
            return self.hub.switch()
          File "/usr/local/lib64/python3.4/site-packages/gevent/hub.py", line 630, in switch
            return RawGreenlet.switch(self)
        socket.timeout: The read operation timed out
        
        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.

...

        STRUCTURED: time=2017-05-22T17:39:00.349005-00 pid=24911
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000049.tar.lzo.
        HINT: The absolute S3 key is postgres/wal-e/basebackups_005/base_0000000100000819000000B0_00000032/tar_partitions/part_00000049.tar.lzo.
        STRUCTURED: time=2017-05-22T17:39:39.551965-00 pid=24911
lzop: Inappropriate ioctl for device: <stdin>
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/usr/local/lib/python3.4/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.4/site-packages/wal_e/worker/s3/s3_worker.py", line 83, in fetch_partition
            raise exc
          File "/usr/local/lib/python3.4/site-packages/wal_e/blobstore/s3/s3_util.py", line 200, in write_and_return_error
            key.get_contents_to_file(stream)
          File "/usr/local/lib/python3.4/site-packages/boto/s3/key.py", line 1650, in get_contents_to_file
            response_headers=response_headers)
          File "/usr/local/lib/python3.4/site-packages/boto/s3/key.py", line 1482, in get_file
            query_args=None)
          File "/usr/local/lib/python3.4/site-packages/boto/s3/key.py", line 1535, in _get_file_internal
            for bytes in self:
          File "/usr/local/lib/python3.4/site-packages/boto/s3/key.py", line 386, in next
            data = self.resp.read(self.BufferSize)
          File "/usr/local/lib/python3.4/site-packages/boto/connection.py", line 413, in read
            return http_client.HTTPResponse.read(self, amt)
          File "/usr/lib64/python3.4/http/client.py", line 529, in read
            return super(HTTPResponse, self).read(amt)
          File "/usr/lib64/python3.4/http/client.py", line 568, in readinto
            n = self.fp.readinto(b)
          File "/usr/lib64/python3.4/socket.py", line 374, in readinto
            return self._sock.recv_into(b)
          File "/usr/local/lib64/python3.4/site-packages/gevent/_ssl3.py", line 473, in recv_into
            return self.read(nbytes, buffer)
          File "/usr/local/lib64/python3.4/site-packages/gevent/_ssl3.py", line 295, in read
            self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)
          File "/usr/local/lib64/python3.4/site-packages/gevent/_socket3.py", line 157, in _wait
            self.hub.wait(watcher)
          File "/usr/local/lib64/python3.4/site-packages/gevent/hub.py", line 651, in wait
            result = waiter.get()
          File "/usr/local/lib64/python3.4/site-packages/gevent/hub.py", line 899, in get
            return self.hub.switch()
          File "/usr/local/lib64/python3.4/site-packages/gevent/hub.py", line 630, in switch
            return RawGreenlet.switch(self)
        socket.timeout: The read operation timed out
        
        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
```

I have seen other posts that indicate using different wal-e version may cause this issue, but in my case the wal-e version is the same:

**HostA**:
```
[bash:~ ] $ wal-e version
1.0.3
```

**HostB**:
```
-bash-4.2$ wal-e version
1.0.3
```

Any assistance is much appreciated.

**Comment by matthewoldham** [comment]
Also tried the following workaround on HostB, but it fails:

```
[root ~]# echo 0 > /proc/sys/fs/pipe-user-pages-soft
-bash: /proc/sys/fs/pipe-user-pages-soft: No such file or directory

```

**Comment by fdr** [comment]
That's weird. Although, it looks like there may be a timeout at the root of this?

**Comment by tschwaerzl** [comment]
Just adding myself here. Got the very same problem. 

Maybe interesting: I tested WAL-E before with Ubuntu 16.04 and everything worked fine. Now I'm testing with Ubuntu 14.04 and got the error.

**Comment by matthewoldham** [comment]
Yes, it appears to have been related to a timeout issue in my situation, which I have seen several times since. It does not seem to cause any problems with the restore, so I assume it's automatically retrying and succeeding?  It's hard to tell from the log messages.

**Comment by tschwaerzl** [comment]
Can confirm, errors randomly show up but `backup-fetch` still works. Just restored around 300 GiB

**Comment by tschwaerzl** [comment]
I did some further research on this. As you can see wal-e finished downloading and flushing `part_00000001.tar.lzo` ('completed stream writing' & 'flush complete') but in `swift_worker` it tries to work with `part_00000000.tar.lzo` which download hasn't finished yet.

```bash
# sudo -u postgres /usr/bin/envdir /etc/wal-e.d/env /opt/wal-e/bin/wal-e backup-fetch /var/lib/postgresql/9.5/main_tmp base_0000000100000167000000CA_00000040
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-fetch".
        STRUCTURED: time=2017-06-28T08:54:20.175173-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000000.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000000.tar.lzo.
        STRUCTURED: time=2017-06-28T08:54:22.520874-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: gevent.spanwed
        DETAIL: gevent "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000000.tar.lzo"
        STRUCTURED: time=2017-06-28T08:54:22.522475-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000001.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000001.tar.lzo.
        STRUCTURED: time=2017-06-28T08:54:22.522849-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: gevent.spanwed
        DETAIL: gevent "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000001.tar.lzo"
        STRUCTURED: time=2017-06-28T08:54:22.523900-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000002.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000002.tar.lzo.
        STRUCTURED: time=2017-06-28T08:54:22.524191-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: gevent.spanwed
        DETAIL: gevent "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000002.tar.lzo"
        STRUCTURED: time=2017-06-28T08:54:22.525233-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000003.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000003.tar.lzo.
        STRUCTURED: time=2017-06-28T08:54:22.525515-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: gevent.spanwed
        DETAIL: gevent "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000003.tar.lzo"
        STRUCTURED: time=2017-06-28T08:54:22.526545-00 pid=26339
wal_e.blobstore.swift.utils INFO     MSG: completed stream writing
        DETAIL: Stream "swift://cloud/basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000001.tar.lzo"
        STRUCTURED: time=2017-06-28T08:54:54.900829-00 pid=26339
wal_e.blobstore.swift.utils INFO     MSG: flush complete
        DETAIL: Stream "swift://cloud/basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000001.tar.lzo"
        STRUCTURED: time=2017-06-28T08:54:54.901228-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: tarpartition
        DETAIL: tarpartition "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000001.tar.lzo"
        STRUCTURED: time=2017-06-28T08:55:05.585873-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000004.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000004.tar.lzo.
        STRUCTURED: time=2017-06-28T08:55:05.713832-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: gevent.spanwed
        DETAIL: gevent "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000004.tar.lzo"
        STRUCTURED: time=2017-06-28T08:55:05.716030-00 pid=26339
lzop: Inappropriate ioctl for device: <stdin>
wal_e.worker.swift.swift_worker INFO     MSG: tarpartition
        DETAIL: tarpartition "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000000.tar.lzo"
        STRUCTURED: time=2017-06-28T08:55:30.598905-00 pid=26339
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/opt/wal-e/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 302, in _error_catcher
            yield
          File "/opt/wal-e/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 384, in read
            data = self._fp.read(amt)
          File "/usr/lib/python3.4/http/client.py", line 529, in read
            return super(HTTPResponse, self).read(amt)
          File "/usr/lib/python3.4/http/client.py", line 568, in readinto
            n = self.fp.readinto(b)
        RuntimeError: reentrant call inside <_io.BufferedReader name=14>

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/worker/swift/swift_worker.py", line 80, in fetch_partition
            raise exc
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/blobstore/swift/utils.py", line 147, in write_and_return_error
            for chunk in response:
          File "/opt/wal-e/lib/python3.4/site-packages/swiftclient/client.py", line 269, in __next__
            return self.next()
          File "/opt/wal-e/lib/python3.4/site-packages/swiftclient/client.py", line 263, in next
            buf = self.read(self.chunk_size)
          File "/opt/wal-e/lib/python3.4/site-packages/swiftclient/client.py", line 308, in read
            buf = self.resp.read(length)
          File "/opt/wal-e/lib/python3.4/site-packages/swiftclient/client.py", line 460, in releasing_read
            chunk = self.resp.raw.read(*args, **kwargs)
          File "/opt/wal-e/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 401, in read
            raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
          File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
            self.gen.throw(type, value, traceback)
          File "/opt/wal-e/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 333, in _error_catcher
            self._original_response.close()
          File "/usr/lib/python3.4/http/client.py", line 491, in close
            self._close_conn()
          File "/usr/lib/python3.4/http/client.py", line 486, in _close_conn
            fp.close()
        RuntimeError: reentrant call inside <_io.BufferedReader name=14>

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2017-06-28T08:55:30.615722-00 pid=26339
lzop: <stdin>: Compressed data violation
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000000.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000000.tar.lzo.
        STRUCTURED: time=2017-06-28T08:55:30.716339-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: gevent.spanwed
        DETAIL: gevent "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000000.tar.lzo"
        STRUCTURED: time=2017-06-28T08:55:30.718715-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: tarpartition
        DETAIL: tarpartition "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000003.tar.lzo"
        STRUCTURED: time=2017-06-28T08:55:30.831710-00 pid=26339
lzop: Inappropriate ioctl for device: <stdin>
lzop: <stdin>: Compressed data violation
wal_e.worker.swift.swift_worker INFO     MSG: tarpartition
        DETAIL: tarpartition "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000004.tar.lzo"
        STRUCTURED: time=2017-06-28T08:55:31.307368-00 pid=26339
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/opt/wal-e/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 302, in _error_catcher
            yield
          File "/opt/wal-e/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 384, in read
            data = self._fp.read(amt)
          File "/usr/lib/python3.4/http/client.py", line 529, in read
            return super(HTTPResponse, self).read(amt)
          File "/usr/lib/python3.4/http/client.py", line 568, in readinto
            n = self.fp.readinto(b)
        RuntimeError: reentrant call inside <_io.BufferedReader name=24>

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/worker/swift/swift_worker.py", line 80, in fetch_partition
            raise exc
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/blobstore/swift/utils.py", line 147, in write_and_return_error
            for chunk in response:
          File "/opt/wal-e/lib/python3.4/site-packages/swiftclient/client.py", line 269, in __next__
            return self.next()
          File "/opt/wal-e/lib/python3.4/site-packages/swiftclient/client.py", line 263, in next
            buf = self.read(self.chunk_size)
          File "/opt/wal-e/lib/python3.4/site-packages/swiftclient/client.py", line 308, in read
            buf = self.resp.read(length)
          File "/opt/wal-e/lib/python3.4/site-packages/swiftclient/client.py", line 460, in releasing_read
            chunk = self.resp.raw.read(*args, **kwargs)
          File "/opt/wal-e/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 401, in read
            raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
          File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
            self.gen.throw(type, value, traceback)
          File "/opt/wal-e/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 333, in _error_catcher
            self._original_response.close()
          File "/usr/lib/python3.4/http/client.py", line 491, in close
            self._close_conn()
          File "/usr/lib/python3.4/http/client.py", line 486, in _close_conn
            fp.close()
        RuntimeError: reentrant call inside <_io.BufferedReader name=24>

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2017-06-28T08:55:31.307850-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: tarpartition
        DETAIL: tarpartition "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000002.tar.lzo"
        STRUCTURED: time=2017-06-28T08:55:31.374181-00 pid=26339
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/worker/swift/swift_worker.py", line 80, in fetch_partition
            raise exc
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/blobstore/swift/utils.py", line 148, in write_and_return_error
            stream.write(chunk)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/pipebuf.py", line 260, in write
            flushed = self._partial_flush(65535)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/pipebuf.py", line 234, in _partial_flush
            n = os.write(self._fd, cursor)
        BrokenPipeError: [Errno 32] Broken pipe

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2017-06-28T08:55:31.381459-00 pid=26339
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/worker/swift/swift_worker.py", line 80, in fetch_partition
            raise exc
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/blobstore/swift/utils.py", line 148, in write_and_return_error
            stream.write(chunk)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/pipebuf.py", line 260, in write
            flushed = self._partial_flush(65535)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/pipebuf.py", line 234, in _partial_flush
            n = os.write(self._fd, cursor)
        BrokenPipeError: [Errno 32] Broken pipe

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2017-06-28T08:55:31.381778-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000004.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000004.tar.lzo.
        STRUCTURED: time=2017-06-28T08:55:31.505915-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: gevent.spanwed
        DETAIL: gevent "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000004.tar.lzo"
        STRUCTURED: time=2017-06-28T08:55:31.508116-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000002.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000002.tar.lzo.
        STRUCTURED: time=2017-06-28T08:55:31.508541-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: gevent.spanwed
        DETAIL: gevent "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000002.tar.lzo"
        STRUCTURED: time=2017-06-28T08:55:31.509921-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000003.tar.lzo.
        HINT: The absolute Swift object name is basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000003.tar.lzo.
        STRUCTURED: time=2017-06-28T08:55:31.510261-00 pid=26339
wal_e.worker.swift.swift_worker INFO     MSG: gevent.spanwed
        DETAIL: gevent "basebackups_005/base_0000000100000167000000CA_00000040/tar_partitions/part_00000003.tar.lzo"
        STRUCTURED: time=2017-06-28T08:55:31.511557-00 pid=26339```

**Comment by koen-serry** [comment]
Anyone got around this, trying to restore a backup on ubuntu 18.08 made on 14.0. 
FYI both 330 and this one were closed.

Wal-e versions match to 1.10, both have lzop v1.03

**Comment by chobostar** [comment]
we got the same issue on:
    Linux 4.16.9-1-ARCH
    wal-e 1.1.0

it's some king of concurrency issue:
reducing `--pool-size 1` helps

**Comment by t0k4rt** [comment]
same issue here with
wal-e 1.1.0
python 3.4.10
ubuntu 18.04
`--pool-size 1` also helps
