### ISSUE TITLE
Problem recovering GPG encrypted backups

### ISSUE THREAD

**Issue by sauliusgrigaitis** [wal-e/wal-e#341]
I'm trying to setup wal-e `1.0.3` backups with GPG encryption, but I get this error when recovering. Recover works well when backups are not encrypted.

```
lzop: <stdin>: not a lzop file
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/usr/lib/python3.4/tarfile.py", line 2249, in next
            tarinfo = self.tarinfo.fromtarfile(self)
          File "/usr/lib/python3.4/tarfile.py", line 1083, in fromtarfile
            obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
          File "/usr/lib/python3.4/tarfile.py", line 1019, in frombuf
            raise EmptyHeaderError("empty header")
        tarfile.EmptyHeaderError: empty header
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/s3/s3_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/tar_partition.py", line 268, in tarfile_extract
            bufsize=pipebuf.PIPE_BUF_BYTES)
          File "/usr/lib/python3.4/tarfile.py", line 1578, in open
            t = cls(name, filemode, stream, **kwargs)
          File "/usr/lib/python3.4/tarfile.py", line 1470, in __init__
            self.firstmember = self.next()
          File "/usr/lib/python3.4/tarfile.py", line 2264, in next
            raise ReadError("empty file")
        tarfile.ReadError: empty file
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/local/lib/python3.4/dist-packages/wal_e/pipeline.py", line 107, in __exit__
            self.stdin.flush()
          File "/usr/local/lib/python3.4/dist-packages/wal_e/pipebuf.py", line 264, in flush
            self._partial_flush(0)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/pipebuf.py", line 234, in _partial_flush
            n = os.write(self._fd, cursor)
        BrokenPipeError: [Errno 32] Broken pipe
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/local/lib/python3.4/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/s3/s3_worker.py", line 83, in fetch_partition
            raise exc
          File "/usr/local/lib/python3.4/dist-packages/wal_e/pipeline.py", line 120, in __exit__
            raise exc_type(exc_value).with_traceback(traceback)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/worker/s3/s3_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/tar_partition.py", line 268, in tarfile_extract
            bufsize=pipebuf.PIPE_BUF_BYTES)
          File "/usr/lib/python3.4/tarfile.py", line 1578, in open
            t = cls(name, filemode, stream, **kwargs)
          File "/usr/lib/python3.4/tarfile.py", line 1470, in __init__
            self.firstmember = self.next()
          File "/usr/lib/python3.4/tarfile.py", line 2264, in next
            raise ReadError("empty file")
        tarfile.ReadError: empty file
        
        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2017-06-06T11:41:26.853813-00 pid=70
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000000.tar.lzo.
        HINT: The absolute S3 key is wal/basebackups_005/base_000000010000000700000013_00000040/tar_partitions/part_00000000.tar.lzo.
        STRUCTURED: time=2017-06-06T11:41:26.955593-00 pid=70
```

**Comment by sauliusgrigaitis** [comment]
Does anyone use GPG encryption with wal-e and can confirm that it actually works?

**Comment by deverant** [comment]
Hey @sauliusgrigaitis,

I can confirm that GPG encryption does indeed work, but I have had issues in the past with it. I think the first thing to do is to double check that the files in your storage are not corrupt. I'd download one of the WAL files from your storage and run GPG manually on it to decrypt it and then try to lzop decompress the file. Those are basically the two commands wal-e runs on the file with some added piping in there that we don't need to care about for now.

Is this something you could check?

**Comment by trojanowski** [comment]
Hi @sauliusgrigaitis,

I had the same problem. The solution was to add the `s3:GetObjectVersion` permission to the S3 bucket policy.

**Comment by sauliusgrigaitis** [comment]
Thanks @deverant and @trojanowski . Looks like now it fetches correctly from the S3, but I did hit another strange case. Looks like it correctly recovers base backup and first WAL segment, but it fails to process second WAL segment and simply keeps repeating it. Any ideas?

```
LOG:  entering standby mode
wal_e.operator.backup INFO     MSG: begin wal restore
        STRUCTURED: time=2017-06-14T17:17:11.918011-00 pid=126 action=wal-fetch key=s3://<bucket>/wal/wal_005/0000000100000008000000A7.lzo prefix=wal/ seg=0000000100000008000000A7 state=begin 
FATAL:  the database system is starting up
wal_e.blobstore.s3.s3_util INFO     MSG: completed download and decompression
        DETAIL: Downloaded and decompressed "s3://<bucket>/wal/wal_005/0000000100000008000000A7.lzo" to "pg_xlog/RECOVERYXLOG"
        STRUCTURED: time=2017-06-14T17:17:12.843721-00 pid=126
wal_e.operator.backup INFO     MSG: complete wal restore
        STRUCTURED: time=2017-06-14T17:17:12.847112-00 pid=126 action=wal-fetch key=s3://<bucket>/wal/wal_005/0000000100000008000000A7.lzo prefix=wal/ seg=0000000100000008000000A7 state=complete
LOG:  restored log file "0000000100000008000000A7" from archive
FATAL:  the database system is starting up
LOG:  redo starts at 8/A7000028
LOG:  consistent recovery state reached at 8/A7007070
FATAL:  the database system is starting up
wal_e.operator.backup INFO     MSG: begin wal restore
        STRUCTURED: time=2017-06-14T17:17:14.787072-00 pid=163 action=wal-fetch key=s3://<bucket>/wal/wal_005/0000000100000008000000A8.lzo prefix=wal/ seg=0000000100000008000000A8 state=begin 
FATAL:  the database system is starting up
gpg: decrypt_message failed: eof
wal_e.blobstore.s3.s3_util INFO     MSG: could no longer locate object while performing wal restore
        DETAIL: The absolute URI that could not be located is s3://<bucket>/wal/wal_005/0000000100000008000000A8.lzo.
        HINT: This can be normal when Postgres is trying to detect what timelines are available during restoration.
        STRUCTURED: time=2017-06-14T17:17:15.435060-00 pid=163
lzop: <stdin>: not a lzop file
wal_e.operator.backup INFO     MSG: complete wal restore
        STRUCTURED: time=2017-06-14T17:17:15.536861-00 pid=163 action=wal-fetch key=s3://<bucket>/wal/wal_005/0000000100000008000000A8.lzo prefix=wal/ seg=0000000100000008000000A8 state=complete
FATAL:  the database system is starting up
wal_e.operator.backup INFO     MSG: begin wal restore
        STRUCTURED: time=2017-06-14T17:17:17.151558-00 pid=177 action=wal-fetch key=s3://<bucket>/wal/wal_005/0000000100000008000000A8.lzo prefix=wal/ seg=0000000100000008000000A8 state=begin 
FATAL:  the database system is starting up
gpg: wal_e.blobstore.s3.s3_util INFO     MSG: could no longer locate object while performing wal restore
        DETAIL: The absolute URI that could not be located is s3://<bucket>/wal/wal_005/0000000100000008000000A8.lzo.
        HINT: This can be normal when Postgres is trying to detect what timelines are available during restoration.
        STRUCTURED: time=2017-06-14T17:17:17.740944-00 pid=177
decrypt_message failed: eof
lzop: <stdin>: not a lzop file
wal_e.operator.backup INFO     MSG: complete wal restore
        STRUCTURED: time=2017-06-14T17:17:17.844363-00 pid=177 action=wal-fetch key=s3://<bucket>/wal/wal_005/0000000100000008000000A8.lzo prefix=wal/ seg=0000000100000008000000A8 state=complete
```

**Comment by sauliusgrigaitis** [comment]
Looks like that's how it should actually work as it simply tries to indefinitely fetch next wal archive.
