### ISSUE TITLE
backup-list ans backup-fetch does not works with swift storage

### ISSUE THREAD

**Issue by vgramer** [wal-e/wal-e#356]
Hello,
i am using the swift storage. The _wal archiving_ and the _backup-push_ work correclty. In the container there are two folders: __wal_005__ (which contains the compressed wall files) and __basebackups_005__ (which contains the backup)

I created a backup with this command:
```
[root@blue-db-01 data]# sudo -u postgres bash -c "WALE_SWIFT_PREFIX='swift://TEST' SWIFT_AUTHURL='https://xxxxx' SWIFT_REGION='RegionOne' SWIFT_TENANT='xxxxx' SWIFT_USER='xxxxx' SWIFT_PASSWORD='6b6b6505d1ae996216d650bbfd2d107d' /bin/wal-e backup-push /myproject/pg/data "
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2017-08-22T08:23:14.207345-00 pid=28333
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to swift://TEST/basebackups_005/base_0000000100000003000000F2_00000040/extended_version.txt.
        STRUCTURED: time=2017-08-22T08:23:14.659697-00 pid=28333
wal_e.operator.backup INFO     MSG: postgres version metadata upload complete
        STRUCTURED: time=2017-08-22T08:23:15.050084-00 pid=28333
wal_e.worker.upload INFO     MSG: beginning volume compression
        DETAIL: Building volume 0.
        STRUCTURED: time=2017-08-22T08:23:15.138564-00 pid=28333
wal_e.worker.upload INFO     MSG: begin uploading a base backup volume
        DETAIL: Uploading to "swift://TEST/basebackups_005/base_0000000100000003000000F2_00000040/tar_partitions/part_00000000.tar.lzo".
        STRUCTURED: time=2017-08-22T08:23:16.100554-00 pid=28333
wal_e.worker.upload INFO     MSG: finish uploading a base backup volume
        DETAIL: Uploading to "swift://TEST/basebackups_005/base_0000000100000003000000F2_00000040/tar_partitions/part_00000000.tar.lzo" complete at 32545.7KiB/s. 
        STRUCTURED: time=2017-08-22T08:23:17.279654-00 pid=28333
NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
```

the backup is correctly pushed. In my container i have the following files:

```
── BASEBACKUPS_005
    ├── base_0000000100000003000000F2_00000040
    │   ├── extended_version.txt
    │   └── tar_partitions
    │       └── part_00000000.tar.lzo
    └── base_0000000100000003000000F2_00000040_backup_stop_sentinel.json
```
But when i run an __backup-flist__ i get no result:

```
[root@blue-db-01 data]# sudo -u postgres bash -c "WALE_SWIFT_PREFIX='swift://TEST' SWIFT_AUTHURL='https://xxxxx' SWIFT_REGION='RegionOne' SWIFT_TENANT='xxxxx' SWIFT_USER='xxxxx' SWIFT_PASSWORD='6b6b6505d1ae996216d650bbfd2d107d' /bin/wal-e backup-list "
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-list".
        STRUCTURED: time=2017-08-22T08:23:41.242747-00 pid=28399
name	last_modified	expanded_size_bytes	wal_segment_backup_start	wal_segment_offset_backup_start	wal_segment_backup_stop	wal_segment_offset_backup_stop
```

I have the follwing confguration:

- Os: centos 7
- pythons: 3.4.5
- wal-e: 1.0.3
- postgresql: 9.6
- $PGDATA: /myproject/pg/data

Best regards

**Comment by Slach** [comment]
i see the same problem

when try run backup-fetch  with swift for python3.4 and 3.5
i have following traceback

# python 3.4

```
lzop: Inappropriate ioctl for device: <stdin>
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/home/wal-e/venv3.4/lib/python3.4/site-packages/wal_e/retries.py", line 70, in shim
            return f(*args, **kwargs)
          File "/home/wal-e/venv3.4/lib/python3.4/site-packages/wal_e/worker/swift/swift_worker.py", line 73, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/home/wal-e/venv3.4/lib/python3.4/site-packages/wal_e/tar_partition.py", line 292, in tarfile_extract
            cat_extract(tar, member, relpath)
          File "/home/wal-e/venv3.4/lib/python3.4/site-packages/wal_e/tar_partition.py", line 220, in cat_extract
            copyfileobj.copyfileobj(fp, pl.stdin)
          File "/home/wal-e/venv3.4/lib/python3.4/site-packages/wal_e/copyfileobj.py", line 15, in copyfileobj
            shutil.copyfileobj(src, dst, BUFSIZE)
          File "/usr/lib/python3.4/shutil.py", line 67, in copyfileobj
            buf = fsrc.read(length)
          File "/usr/lib/python3.4/tarfile.py", line 704, in readinto
            buf = self.read(len(b))
          File "/usr/lib/python3.4/tarfile.py", line 695, in read
            raise ReadError("unexpected end of data")
        tarfile.ReadError: unexpected end of data
```

# python 3.5
```
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/usr/local/lib/python3.5/dist-packages/wal_e/retries.py", line 70, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/worker/swift/swift_worker.py", line 73, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/tar_partition.py", line 292, in tarfile_extract
            cat_extract(tar, member, relpath)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/tar_partition.py", line 220, in cat_extract
            copyfileobj.copyfileobj(fp, pl.stdin)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/copyfileobj.py", line 17, in copyfileobj
            shutil.copyfileobj(src, dst, BUFSIZE)
          File "/usr/lib/python3.5/shutil.py", line 73, in copyfileobj
            buf = fsrc.read(length)
          File "/usr/lib/python3.5/tarfile.py", line 698, in readinto
            buf = self.read(len(b))
          File "/usr/lib/python3.5/tarfile.py", line 689, in read
            raise ReadError("unexpected end of data")
        tarfile.ReadError: unexpected end of data
```

**Comment by fdr** [comment]
Consider installing from "master". You may be seeing a bug in python 3.x's symlink handling.

**Comment by Slach** [comment]
i'm install wal-e over
```
pip install https://github.com/wal-e/wal-e/archive/master.zip
``` 
and try with python3.5 and python3.4 under ubuntu 16.04

**Comment by vgramer** [comment]
Hello, 

I think my problem is different from the one of @Slach . I don't have a python exception. I set log level to DEBUG and find the problem:

```
swiftclient  DEBUG    REQ: curl -i https://object-store.api.entreprise.com/swift/v1/TEST?format=json&prefix=/basebackups_005/ -X GET -H "Accept-Encoding: gzip" -H "X-Auth-Token: gAAAAABZn_Msqy6T..."
swiftclient  DEBUG    RESP STATUS: 200 OK
swiftclient  DEBUG    RESP HEADERS: {'X-Timestamp': '1503653193.00000', 'X-Storage-Policy': 'default-placement', 'Server': 'nginx', 'X-Container-Bytes-Used': '117465295', 'X-Container-Object-Count': '9', 'Content-Length': '2', 'Content-Type': 'application/json; charset=utf-8', 'X-Container-Bytes-Used-Actual': '117497856', 'Content-Security-Policy': "form-action 'none'; default-src 'self';", 'Accept-Ranges': 'bytes', 'X-Trans-Id': 'tx00000000000000076705a-00599ff32c-165797-default', 'Connection': 'keep-alive', 'Date': 'Fri, 25 Aug 2017 09:51:41 GMT'}
swiftclient  DEBUG    RESP BODY: b'[]'
```

The response code HTTP 200 with an empty body. The request is incorrect, the prefix should not with a slash. 
The resquest should be:

```
curl -i https://object-store.api.entreprise.com/swift/v1/TEST?format=json&prefix=basebackups_005/ -X GET -H "Accept-Encoding: gzip" -H "X-Auth-Token: gAAAAABZn_Msqy6T..."
```

In class /worker/swift/swift_worker.py, we can see that a slash is inserted before the prefix value https://github.com/wal-e/wal-e/blob/fc4363def7b3ce9306f613b31722f46f853dfe4e/wal_e/worker/swift/swift_worker.py#L86-L88
If i remove it, the backup-list works correclty.


```
base_00000001000000000000000B_00000040	2017-08-25T09:50:01.000Z		00000001000000000000000B	00000040		
base_00000001000000000000000D_00000040	2017-08-25T09:51:21.000Z		00000001000000000000000D	00000040		
base_00000001000000000000000F_00000040	2017-08-25T09:51:33.000Z		00000001000000000000000F	00000040
```

But I m not sure it's right way to fix it. Can you confirm it ?

Best regards

**Comment by atipugin** [comment]
I'm experiencing same issue. @vgramer have you solved it?

**Comment by vgramer** [comment]
Hello @atipugin,

Not really, finally we choose another solution. 

However removing the slash before the prefix in class `/worker/swift/swift_worker.py`,  seems to works. 

Another solution may to use the S3 api if you're Swift is compatible with.

**Comment by atipugin** [comment]
@vgramer got you. This PR https://github.com/wal-e/wal-e/pull/342 attempts to fix it, but looks like it will never be merged :( Going to maintain own fork for now, coz S3 isn't an option for me
