### ISSUE TITLE
Can not import BlobService

### ISSUE THREAD

**Issue by andrewgy8** [wal-e/wal-e#358]
Im attempting to run wal-e[Azure] in a postgres container.  When I run my command 

`/usr/bin/envdir /etc/wal-e.d/env wal-e backup-push /var/lib/postgresql/data`

I get back the error:
```
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2017-09-04T15:21:52.691678-00 pid=1853
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/wabs/wabs_util.py", line 27, in <module>
            from azure.storage.blob import BlobService
        ImportError: cannot import name 'BlobService'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/local/lib/python3.4/dist-packages/wal_e/cmd.py", line 589, in main
            backup_cxt = configure_backup_cxt(args)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/cmd.py", line 504, in configure_backup_cxt
            from wal_e.blobstore import wabs
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/wabs/__init__.py", line 11, in <module>
            from wal_e.blobstore.wabs.wabs_util import do_lzop_get
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/wabs/wabs_util.py", line 29, in <module>
            from azure.storage import BlobService
        ImportError: cannot import name 'BlobService'
        
        STRUCTURED: time=2017-09-04T15:21:52.768201-00 pid=1853
```

I went ahead and checked that `azure` and `azure-storage` were successfully installed with `pip3 install azure azure-storage` and yes, all requirements were met. 

The way i installed wal-e was by `python3 -m pip install wal-e[azure]`.

Any ideas?

**Comment by andrewgy8** [comment]
After some digging around, I found the answer.  

Apparently, after `azure` < 0.20.0, the import of `BlobStorage` is split in two. Therefore I needed to install `pip install azure-storage==0.20.0` explicitly.  

Then vóila!
