### ISSUE TITLE
WALE_FILE_PREFIX doesn't work

### ISSUE THREAD

**Issue by mikemcrill** [wal-e/wal-e#362]
While using WAL-E 1.0.3 on Debian/stretch, I receive the following error when trying to use WALE to backup locally (for testing):

```
root@dev-psql:/home/vagrant# WALE_STORAGE=filesystem WALE_FILE_PREFIX=file://localhost/backups/pg wal-e backup-push /var/lib/postgresql/9.6/main
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2017-09-19T13:19:46.785363-00 pid=10808
wal_e.main   ERROR    MSG: no storage prefix defined
        HINT: Either set one of the --wabs-prefix, --s3-prefix or --gs-prefix options or define one of the WALE_WABS_PREFIX, WALE_S3_PREFIX, WALE_SWIFT_PREFIX or WALE_GS_PREFIX environment variables.
        STRUCTURED: time=2017-09-19T13:19:46.786320-00 pid=10808
```

**Comment by AlexGilleran** [comment]
Same problem here. [Looks like it's in the readme but hasn't been released yet](https://github.com/wal-e/wal-e/commits/master/README.rst) :( 

Is there a pending release that's going to add this functionality? If not it'd be cool if you could add a note to the readme that it's not actually available yet, this completely confused me :(.

**Comment by yagooar** [comment]
I'm seeing the same issue here. `WALE_FILE_PREFIX` does not seem to be honored by the latest `wal-e` release. Any way to solve this issue?

**Comment by rohit-smpx** [comment]
Installing from source fixes this issue. Though I'm not sure if that should be used in production, for testing purposes it's fine.

**Comment by yagooar** [comment]
Any maintainer will to share if the feature is going to be released officially any time soon?

**Comment by iJebus** [comment]
This seems to be working fine for me in WAL-E version 1.1.0.

**Comment by arunvc** [comment]
its working fine with 1.1.0

but throws another error

```
 --- Logging error ---
Traceback (most recent call last):
   File "/usr/lib/python3.6/logging/handlers.py", line 939, in emit
     self._connect_unixsocket(self.address)
   File "/usr/lib/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
     self.socket.connect(address)
   File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
     raise error(result, strerror(result))
 FileNotFoundError: [Errno 2] No such file or directory
 Call stack:
   File "/usr/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
     result = self._run(*self.args, **self.kwargs)
   File "/usr/lib/python3.6/site-packages/wal_e/worker/upload.py", line 71, in __call__
     structured=structured)
   File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 200, in info
     self.log(logging.INFO, *args, **kwargs)
   File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 189, in log
     *args, **kwargs)
 Message: 'MSG: completed archiving to a file\nDETAIL: Archiving to "file://localhost/var/backups/wal_005/000000010000000000000002.lzo" complete at 133732KiB/s.\nSTRUCTURED: time=2018-04-05T15:49:41.589544-00 pid=80 action=push-wal key=file://localhost/var/backups/wal_005/000000010000000000000002.lzo prefix=var/backups/ rate=133732 seg=000000010000000000000002 state=complete
```
