### ISSUE TITLE
No module named wal_e.cmd 

### ISSUE THREAD

**Issue by andrewgy8** [wal-e/wal-e#363]
In my recovery.conf file I have `restore_command = 'envdir /etc/wal-e.d/env /usr/local/bin/wal-e wal-fetch "%f" "%p"'`. 

However, when I start up postgres 9.6, I run `sudo service postgresql restart` and view `/var/log/syslog` I see:

```
File "/usr/local/bin/wal-e", line 7, in <module>
from wal_e.cmd import main
ImportError: No module named 'wal_e.cmd'
```

Any idea what this could be?

**Comment by andrewgy8** [comment]
Yep, I confirmed my hypothesis.  

When I run  `postgres@solaris-mobile-app:~$ wal-e`

```Traceback (most recent call last):
File "/usr/local/bin/wal-e", line 7, in <module>
    from wal_e.cmd import main
ImportError: No module named 'wal_e.cmd'```

**Comment by andrewgy8** [comment]
I fixed this by doing a fresh installation with a particular order.

1) Install wal-e and dependencies
2) Set up env vars according to the readme.
3) Had to install azure-storage==0.20.0
4) Install postgres 9.6

Then and only then would it work.
