### ISSUE TITLE
wal-e backup-fetch fails | gets s3 access denied

### ISSUE THREAD

**Issue by saurabhkrjha** [wal-e/wal-e#385]
I am getting this error while backup-fetch or backup-list operations, whereas I am able to push backup using same credentials.

```
        boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
        <?xml version="1.0" encoding="UTF-8"?>
        <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C928A0B86173C380</RequestId><HostId>zZ3yDtqgKciBcP0+DetzH/3g7r3M/H9qQzm9s6MQ9z/+RZyQtaDy2KsSOTEiviuiI/85kPIM12I=</HostId></Error>
```

**Comment by MrPostie** [comment]
I have the same problem. Backiup and copy to S3 are no problem but fetch and list won't work. I've tried with different API keys, Group policies and even S3FullAccess, but still getting the Access Denied error.

**Comment by alexwilliamsdr** [comment]
Same here, but haven't tried fetch, I'm trying to delete old backups:

/command/envdir /etc/wal-e.d/env /opt/wal-e/bin/wal-e delete --dry-run --confirm retain 7

wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "delete retain".
        STRUCTURED: time=2019-05-08T17:51:55.011363-00 pid=15488
wal_e.main   INFO     MSG: performing dry run of data deletion
        STRUCTURED: time=2019-05-08T17:51:55.037225-00 pid=15488
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/cmd.py", line 694, in main
            args.NUM_TO_RETAIN)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/operator/backup.py", line 423, in delete_with_retention
            delete_cxt.delete_with_retention(num_to_retain)
          File "/opt/wal-e/lib/python3.4/site-packages/wal_e/worker/base.py", line 446, in delete_with_retention
            for key in self._backup_list(prefix=self.layout.basebackups()):
          File "/opt/wal-e/lib/python3.4/site-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
            encoding_type=encoding_type)
          File "/opt/wal-e/lib/python3.4/site-packages/boto/s3/bucket.py", line 473, in get_all_keys
            '', headers, **params)
          File "/opt/wal-e/lib/python3.4/site-packages/boto/s3/bucket.py", line 411, in _get_all
            response.status, response.reason, body)
        boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
        <?xml version="1.0" encoding="UTF-8"?>
        <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>...</RequestId><HostId>...</HostId></Error>

**Comment by alexwilliamsdr** [comment]
Update to my issue with the above comment left on 2019, the access key I was using didn't have list access, so while it could put / get files, it couldn't do a backup-fetch. Allowing List access on S3 fixed it when trying to run backup-fetch
