### ISSUE TITLE
AWS s3 OSError: [Errno 9] Bad file descriptor during backup-push

### ISSUE THREAD

**Issue by stayfrostnl** [wal-e/wal-e#390]
Hello,

I am trying to get wal-e working inside a docker container. When I execute wal-e as the user postgres the backup succeeds, but i still get a couple a errors inside de traceback. It seems related to gevent and python 3.6. I 'am working with the PostgreSQL alpine 10.3 image and the latest versions of wal-e with the recommended versions of boto and gevent. Any guess why this pops-up ?

wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2018-05-09T10:23:06.763057-00 pid=1931
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 372, in send
    return _socket.socket.send(self._sock, data, flags)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 939, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/bin/wal-e", line 11, in <module>
    load_entry_point('wal-e==1.1.0b1', 'console_scripts', 'wal-e')()
  File "/usr/lib/python3.6/site-packages/wal_e/cmd.py", line 586, in main
    detail='The subcommand is "{0}".'.format(rendered))
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 200, in info
    self.log(logging.INFO, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 189, in log
    *args, **kwargs)
Message: 'MSG: starting WAL-E\nDETAIL: The subcommand is "backup-push".\nSTRUCTURED: time=2018-05-09T10:23:06.763057-00 pid=1931'
Arguments: ()
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to s3://postgresswalle/basebackups_005/base_00000001000000000000000A_00000040/extended_version.txt.
        STRUCTURED: time=2018-05-09T10:23:07.344872-00 pid=1931
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 372, in send
    return _socket.socket.send(self._sock, data, flags)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 939, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/bin/wal-e", line 11, in <module>
    load_entry_point('wal-e==1.1.0b1', 'console_scripts', 'wal-e')()
  File "/usr/lib/python3.6/site-packages/wal_e/cmd.py", line 629, in main
    pool_size=args.pool_size)
  File "/usr/lib/python3.6/site-packages/wal_e/operator/backup.py", line 197, in database_backup
    **kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/operator/backup.py", line 482, in _upload_pg_cluster_dir
    .format(extended_version_url=extended_version_url)))
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 200, in info
    self.log(logging.INFO, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 189, in log
    *args, **kwargs)
Message: 'MSG: start upload postgres version metadata\nDETAIL: Uploading to s3://postgresswalle/basebackups_005/base_00000001000000000000000A_00000040/extended_version.txt.\nSTRUCTURED: time=2018-05-09T10:23:07.344872-00 pid=1931'
Arguments: ()
wal_e.operator.backup INFO     MSG: postgres version metadata upload complete
        STRUCTURED: time=2018-05-09T10:23:07.386090-00 pid=1931
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 372, in send
    return _socket.socket.send(self._sock, data, flags)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 939, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/bin/wal-e", line 11, in <module>
    load_entry_point('wal-e==1.1.0b1', 'console_scripts', 'wal-e')()
  File "/usr/lib/python3.6/site-packages/wal_e/cmd.py", line 629, in main
    pool_size=args.pool_size)
  File "/usr/lib/python3.6/site-packages/wal_e/operator/backup.py", line 197, in database_backup
    **kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/operator/backup.py", line 487, in _upload_pg_cluster_dir
    logger.info(msg='postgres version metadata upload complete')
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 200, in info
    self.log(logging.INFO, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 189, in log
    *args, **kwargs)
Message: 'MSG: postgres version metadata upload complete\nSTRUCTURED: time=2018-05-09T10:23:07.386090-00 pid=1931'
Arguments: ()
wal_e.worker.upload INFO     MSG: beginning volume compression
        DETAIL: Building volume 0.
        STRUCTURED: time=2018-05-09T10:23:07.431735-00 pid=1931
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 372, in send
    return _socket.socket.send(self._sock, data, flags)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 939, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python3.6/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/worker/upload.py", line 90, in __call__
    detail='Building volume {name}.'.format(name=tpart.name))
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 200, in info
    self.log(logging.INFO, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 189, in log
    *args, **kwargs)
Message: 'MSG: beginning volume compression\nDETAIL: Building volume 0.\nSTRUCTURED: time=2018-05-09T10:23:07.431735-00 pid=1931'
Arguments: ()
wal_e.worker.upload INFO     MSG: begin uploading a base backup volume
        DETAIL: Uploading to "s3://postgresswalle/basebackups_005/base_00000001000000000000000A_00000040/tar_partitions/part_00000000.tar.lzo".
        STRUCTURED: time=2018-05-09T10:23:08.257960-00 pid=1931
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 372, in send
    return _socket.socket.send(self._sock, data, flags)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 939, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python3.6/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/worker/upload.py", line 106, in __call__
    detail='Uploading to "{url}".'.format(url=url))
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 200, in info
    self.log(logging.INFO, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 189, in log
    *args, **kwargs)
Message: 'MSG: begin uploading a base backup volume\nDETAIL: Uploading to "s3://postgresswalle/basebackups_005/base_00000001000000000000000A_00000040/tar_partitions/part_00000000.tar.lzo".\nSTRUCTURED: time=2018-05-09T10:23:08.257960-00 pid=1931'
Arguments: ()
wal_e.worker.upload INFO     MSG: finish uploading a base backup volume
        DETAIL: Uploading to "s3://postgresswalle/basebackups_005/base_00000001000000000000000A_00000040/tar_partitions/part_00000000.tar.lzo" complete at 19366.7KiB/s. 
        STRUCTURED: time=2018-05-09T10:23:08.456210-00 pid=1931
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 372, in send
    return _socket.socket.send(self._sock, data, flags)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 939, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.6/site-packages/gevent/_socket3.py", line 295, in connect
    raise error(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python3.6/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/worker/upload.py", line 154, in __call__
    .format(url=url, kib_per_second=kib_per_second)))
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 200, in info
    self.log(logging.INFO, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/wal_e/log_help.py", line 189, in log
    *args, **kwargs)
Message: 'MSG: finish uploading a base backup volume\nDETAIL: Uploading to "s3://postgresswalle/basebackups_005/base_00000001000000000000000A_00000040/tar_partitions/part_00000000.tar.lzo" complete at 19366.7KiB/s. \nSTRUCTURED: time=2018-05-09T10:23:08.456210-00 pid=1931'
Arguments: ()
NOTICE:  WAL archiving is not enabled; you must ensure that all required WAL segments are copied through other means to complete the backup

**Comment by stayfrostnl** [comment]
Aha, I will check it tomorrow. I know it's broken on Python 3.6 , I used the commits for those bugs and changed the code inside my docker image to make it work.

**Comment by stayfrostnl** [comment]
@martyanov  Thanks, that was it. I pulled the master with the latest fixes but this is still not functioning correctly without locally correcting the code to make it work with python 3.6.

**Comment by martyanov** [comment]
@stayfrostnl May be there is another issue. We are successfully running several `PostgreSQL` clusters with `wal-e` without any issues. I haven't tested current `master` branch, though.

**Comment by stayfrostnl** [comment]
I managed to get it working as well. I build an docker image with wal-e and postgreSQL and during the build of that image I have replaced the broken code. It works great and stores its backups in Minio. But i would prefer a working master, so thats why is was asking.
