### ISSUE TITLE
S3: Hacking support for China region

### ISSUE THREAD

**Issue by profilernz** [wal-e/wal-e#391]
Posting here in case this helps someone else...

s3.amazonaws.com is not available when using China IAM credentials, and for some reason wal-e insists on using that even when defining a new cn-north-1 endpoint.

This quick and ugly hack fixed it for us (but will break things for other regions) :

```
diff calling_format.py calling_format.py-original 
23d22
<     'cn-north-1': 's3.cn-north-1.amazonaws.com.cn',
214c213
<             return _conn_help(host='s3.cn-north-1.amazonaws.com.cn')
---
>             return _conn_help(host='s3.amazonaws.com')
```

**Comment by Antiarchitect** [comment]
Please support #392 - it contains both regions in China I suppose.

**Comment by profilernz** [comment]
Just updating the endpoints won't fix it in the case of China because chinese IAM credentials refuse to connect to s3.amazonaws.com (which wal-e seems to need for some reason).
This is a China-only problem (and perhaps GovCloud).

**Comment by Antiarchitect** [comment]
What if you hold backups in Chinese region when wal-e works on Chinese ec2.

**Comment by profilernz** [comment]
Using Chinese EC2, Chinese S3 and Chinese IAM keys, I get:
```
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/wal_e/cmd.py", line 629, in main
            backup_cxt.backup_list(query=args.QUERY, detail=args.detail)
          File "/usr/lib/python3.6/site-packages/wal_e/operator/backup.py", line 66, in backup_list
            for bi in bl_iter:
          File "/usr/lib/python3.6/site-packages/wal_e/worker/base.py", line 153, in __iter__
            for key in self._backup_list(self.layout.basebackups()):
          File "/usr/lib/python3.6/site-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
            encoding_type=encoding_type)
          File "/usr/lib/python3.6/site-packages/boto/s3/bucket.py", line 474, in get_all_keys
            '', headers, **params)
          File "/usr/lib/python3.6/site-packages/boto/s3/bucket.py", line 412, in _get_all
            response.status, response.reason, body)
        boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
        <?xml version="1.0" encoding="UTF-8"?>
        <Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'cn-north-1' is wrong; expecting 'us-east-1'</Message><Region>us-east-1</Region><RequestId>55A9CC3226CB0D32</RequestId><HostId>qx/yQDgQ3ry/1K00kAPb6ePm0WEejqMNa/nhcgvVhimGFsFEuV73+WjK077h6EOP7kUvDLVyyHc=</HostId></Error>
```
