### ISSUE TITLE
Wal-e error: “ pg_stop_backup still waiting for all required WAL segments to be archived”

### ISSUE THREAD

**Issue by proteeti13** [wal-e/wal-e#401]
I've been trying to use wal-e to take incremental backup of my postgresql database by following [this](https://edwardsamuel.wordpress.com/2016/05/24/set-up-scheduled-postgresql-backup-to-aws-s3-using-wal-e/) blog. I've a database on my postgresql and using an AWS S3 bucket. while I'm using the following command

sudo -u postgres /usr/bin/envdir /etc/wal-e.d/env /usr/local/bin/wal-e backup-push /var/lib/postgresql/10/main

it shows this 
![zpcyj](https://user-images.githubusercontent.com/11318378/42743341-c8462236-88e4-11e8-87f1-6ad1a3c13069.png)

Any help on this?

Thanks :)

**Comment by greylord1996** [comment]
@proteeti13 I have faced the same problem today. Have you already solved it?

**Comment by proteeti13** [comment]
Couldn't solve it. I spent a lot of time figuring out but failed. Now started reading the documentation of Barman :( @greylord1996

**Comment by TianyangLi** [comment]
@proteeti13 hey, i'm also experiencing the same issue.

In my case (I'm using digital ocean a s3 interpolated object) its because boto is expecting me to insert a aws:kms key despite the fact i'm not running with aws s3. 

`Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.6/dist-packages/wal_e/worker/upload.py", line 53, in __call__
    self.gpg_key_id)
  File "/usr/local/lib/python3.6/dist-packages/wal_e/worker/worker_util.py", line 40, in do_lzop_put
    k = blobstore.uri_put_file(creds, url, tf)
  File "/usr/local/lib/python3.6/dist-packages/wal_e/blobstore/s3/s3_util.py", line 57, in uri_put_file
    k.set_contents_from_file(fp, encrypt_key=True)
  File "/usr/local/lib/python3.6/dist-packages/boto/s3/key.py", line 1309, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python3.6/dist-packages/boto/s3/key.py", line 762, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python3.6/dist-packages/boto/s3/key.py", line 963, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python3.6/dist-packages/boto/s3/connection.py", line 671, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python3.6/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python3.6/dist-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/usr/local/lib/python3.6/dist-packages/boto/s3/key.py", line 896, in sender
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidArgument</Code><Message>Server Side Encryption with KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms</Message><BucketName>kpex-space</BucketName><RequestId>tx000000000000000208c19$
2018-08-06T01:57:45Z <Greenlet "Greenlet-23" at 0x7f4e1882a348: <wal_e.worker.upload.WalUploader object at 0x7f4e188894a8>(<wal_e.worker.pg.wal_transfer.WalSegment object at)> failed with S3ResponseError`

**Comment by DeathBorn** [comment]
any news here?

**Comment by proteeti13** [comment]
Sorry guys. I couldn't solve it :(

**Comment by DeathBorn** [comment]
just now, noticed that https://github.com/wal-g/wal-g this has configuration regarding kms. maybe that is related
