### ISSUE TITLE
Exception trying to decrypt files that are not encrypted

### ISSUE THREAD

**Issue by omega** [wal-e/wal-e#408]
This might be a rare instance, but we rolled out `WALE_GPG_KEY_ID` in between two `backup-push` jobs, so the base and some wal files are not encrypted, while the last segments are. `backup-pull` with the `WALE_GPG_KEY_ID` set from the start results in a stacktrace and exception. It might be possible to either detect if the file is indeed encrypted, and only attempt decrypting if it is, or catch the exception and show a better error message perhaps.

The stacktrace of one segment:

```
gpg: packet(2) with unknown version 79
lzop: <stdin>: not a lzop file
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/usr/lib/python3.6/tarfile.py", line 2295, in next
            tarinfo = self.tarinfo.fromtarfile(self)
          File "/usr/lib/python3.6/tarfile.py", line 1091, in fromtarfile
            obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
          File "/usr/lib/python3.6/tarfile.py", line 1027, in frombuf
            raise EmptyHeaderError("empty header")
        tarfile.EmptyHeaderError: empty header
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/home/omega/.local/lib/python3.6/site-packages/wal_e/worker/gs/gs_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/home/omega/.local/lib/python3.6/site-packages/wal_e/tar_partition.py", line 269, in tarfile_extract
            bufsize=pipebuf.PIPE_BUF_BYTES)
          File "/usr/lib/python3.6/tarfile.py", line 1599, in open
            t = cls(name, filemode, stream, **kwargs)
          File "/usr/lib/python3.6/tarfile.py", line 1480, in __init__
            self.firstmember = self.next()
          File "/usr/lib/python3.6/tarfile.py", line 2310, in next
            raise ReadError("empty file")
        tarfile.ReadError: empty file
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/home/omega/.local/lib/python3.6/site-packages/wal_e/pipeline.py", line 107, in __exit__
            self.stdin.flush()
          File "/home/omega/.local/lib/python3.6/site-packages/wal_e/pipebuf.py", line 264, in flush
            self._partial_flush(0)
          File "/home/omega/.local/lib/python3.6/site-packages/wal_e/pipebuf.py", line 234, in _partial_flush
            n = os.write(self._fd, cursor)
        BrokenPipeError: [Errno 32] Broken pipe
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/home/omega/.local/lib/python3.6/site-packages/wal_e/retries.py", line 87, in shim
            return f(*args, **kwargs)
          File "/home/omega/.local/lib/python3.6/site-packages/wal_e/worker/gs/gs_worker.py", line 83, in fetch_partition
            raise exc
          File "/home/omega/.local/lib/python3.6/site-packages/wal_e/pipeline.py", line 123, in __exit__
            raise exc_type(exc_value).with_traceback(traceback)
          File "/home/omega/.local/lib/python3.6/site-packages/wal_e/worker/gs/gs_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/home/omega/.local/lib/python3.6/site-packages/wal_e/tar_partition.py", line 269, in tarfile_extract
            bufsize=pipebuf.PIPE_BUF_BYTES)
          File "/usr/lib/python3.6/tarfile.py", line 1599, in open
            t = cls(name, filemode, stream, **kwargs)
          File "/usr/lib/python3.6/tarfile.py", line 1480, in __init__
            self.firstmember = self.next()
          File "/usr/lib/python3.6/tarfile.py", line 2310, in next
            raise ReadError("empty file")
        tarfile.ReadError: empty file
        
        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
```

**Comment by omega** [comment]
It seems to proceed with some retries or something, but the exception could perhaps have been caught and a better warning/info given on the situation

**Comment by omega** [comment]
ooops, duplicate of https://github.com/wal-e/wal-e/issues/109, closing this one, sorry for the noise
