### ISSUE TITLE
wal-e backup-push not working

### ISSUE THREAD

**Issue by umsh1ume** [wal-e/wal-e#415]
```
AWS_SECRET_ACCESS_KEY='xxx' AWS_REGION='ap-southeast-1' wal-e -k 'xxx' --s3-prefix=s3://xxx backup-push /usr/local/var/postgres/
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2019-01-09T07:09:48.871213-00 pid=4841
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to s3://dev-bsapbeat/dms_staging_db_backup/basebackups_005/base_0000000100000008000000F5_00000040/extended_version.txt.
        STRUCTURED: time=2019-01-09T07:09:49.327359-00 pid=4841
wal_e.operator.backup INFO     MSG: postgres version metadata upload complete
        STRUCTURED: time=2019-01-09T07:09:49.638292-00 pid=4841
wal_e.worker.upload INFO     MSG: beginning volume compression
        DETAIL: Building volume 0.
        STRUCTURED: time=2019-01-09T07:09:49.763460-00 pid=4841
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/worker/upload.py", line 97, in __call__
    tpart.tarfile_write(pl.stdin)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/tar_partition.py", line 324, in tarfile_write
    self._padded_tar_add(tar, et_info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/tar_partition.py", line 243, in _padded_tar_add
    tar.addfile(et_info.tarinfo, f)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py", line 1970, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
TypeError: copyfileobj() got an unexpected keyword argument 'bufsize'
2019-01-09T07:09:49Z <Greenlet at 0x10f581598: <wal_e.worker.upload.PartitionUploader object at 0x10f7b9470>([ExtendedTarInfo(submitted_path='/usr/local/var/po)> failed with TypeError

wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2019-01-09T07:09:49.908770-00 pid=4841
NOTICE:  WAL archiving is not enabled; you must ensure that all required WAL segments are copied through other means to complete the backup
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/cmd.py", line 652, in main
            pool_size=args.pool_size)
          File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/operator/backup.py", line 197, in database_backup
            **kwargs)
          File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/operator/backup.py", line 504, in _upload_pg_cluster_dir
            pool.join()
          File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/worker/upload_pool.py", line 120, in join
            self._wait()
          File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/worker/upload_pool.py", line 65, in _wait
            raise val
          File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
          File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/worker/upload.py", line 97, in __call__
            tpart.tarfile_write(pl.stdin)
          File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/tar_partition.py", line 324, in tarfile_write
            self._padded_tar_add(tar, et_info)
          File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wal_e/tar_partition.py", line 243, in _padded_tar_add
            tar.addfile(et_info.tarinfo, f)
          File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tarfile.py", line 1970, in addfile
            copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
        TypeError: copyfileobj() got an unexpected keyword argument 'bufsize'

        STRUCTURED: time=2019-01-09T07:09:50.049182-00 pid=4841
```

**Comment by q8webmaster** [comment]
This is because the latest patch here: #322  Unfortunately is not included in the latest release nor in pip.
