### ISSUE TITLE
Forever waiting for fetch/prefetch when using WALE_FILE_PREFIX

### ISSUE THREAD

**Issue by OrangeDog** [wal-e/wal-e#417]
It appears that because the FileNotFound is unhandled (#396), the recovery process never finishes.

Running commands while stuck:
```
postgres: 10/main: startup process   waiting for 000000010000000F0000000D
sh -c wal-restore 000000010000000F0000000D pg_wal/RECOVERYXLOG
bash /usr/local/sbin/wal-restore 000000010000000F0000000D pg_wal/RECOVERYXLOG
/opt/wal-e/bin/python /usr/local/sbin/wal-e wal-fetch 000000010000000F0000000D /data/postgresql/10/main/pg_wal/RECOVERYXLOG
```

After something has timed out:
```
postgres: 10/main: startup process   recovering 000000010000000F0000000D
/opt/wal-e/bin/python /usr/local/sbin/wal-e wal-prefetch /data/postgresql/10/main/pg_wal 000000010000000F0000000E
/opt/wal-e/bin/python /usr/local/sbin/wal-e wal-prefetch /data/postgresql/10/main/pg_wal 000000010000000F00000011
/opt/wal-e/bin/python /usr/local/sbin/wal-e wal-prefetch /data/postgresql/10/main/pg_wal 000000010000000F00000012
/opt/wal-e/bin/python /usr/local/sbin/wal-e wal-prefetch /data/postgresql/10/main/pg_wal 000000010000000F00000013
/opt/wal-e/bin/python /usr/local/sbin/wal-e wal-prefetch /data/postgresql/10/main/pg_wal 000000010000000F0000000F
/opt/wal-e/bin/python /usr/local/sbin/wal-e wal-prefetch /data/postgresql/10/main/pg_wal 000000010000000F00000014
/opt/wal-e/bin/python /usr/local/sbin/wal-e wal-prefetch /data/postgresql/10/main/pg_wal 000000010000000F00000010
/opt/wal-e/bin/python /usr/local/sbin/wal-e wal-prefetch /data/postgresql/10/main/pg_wal 000000010000000F00000015
```

A bit later it then tries the wal-restore again for the same segment.

**Comment by OrangeDog** [comment]
Have disabled prefetch and it still isn't working.

Logs (repeated every 5 seconds):
```
   INFO     MSG: begin wal restore
        STRUCTURED: time=2019-02-25T15:52:06.655121-00 pid=24392 action=wal-fetch key=file:///mnt/pg_backup/wal_005/000000010000000F0000000D.lzo prefix=mnt/pg_backup/ seg=000000010000000F0000000D state=begin
2019-02-25 15:52:06.767
   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/opt/wal-e/lib/python3.6/site-packages/wal_e/cmd.py", line 657, in main
            args.prefetch)
          File "/opt/wal-e/lib/python3.6/site-packages/wal_e/operator/backup.py", line 353, in wal_restore
            self.gpg_key_id is not None)
          File "/opt/wal-e/lib/python3.6/site-packages/wal_e/worker/worker_util.py", line 58, in do_lzop_get
            return blobstore.do_lzop_get(creds, url, path, decrypt, do_retry=do_retry)
          File "/opt/wal-e/lib/python3.6/site-packages/wal_e/blobstore/file/file_util.py", line 52, in do_lzop_get
            raise exc
          File "/opt/wal-e/lib/python3.6/site-packages/wal_e/blobstore/file/file_util.py", line 64, in write_and_return_error
            key.get_contents_to_file(stream)
          File "/opt/wal-e/lib/python3.6/site-packages/wal_e/blobstore/file/calling_format.py", line 53, in get_contents_to_file
            with open(self.path, 'rb') as f:
        FileNotFoundError: [Errno 2] No such file or directory: '/mnt/pg_backup/wal_005/000000010000000F0000000D.lzo'
        
        STRUCTURED: time=2019-02-25T15:52:06.766014-00 pid=24392
```

Running the same wal-fetch from the command-line exits with status 2 and the error
> lzop: \<stdin>: not a lzop file

**Comment by OrangeDog** [comment]
The recovering server had `standby_mode = on`.
