### ISSUE TITLE
TypeError: copyfileobj() takes from 2 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by scalp42** [wal-e/wal-e#422]
When trying to restore a base backup from S3, the following errors appear:

```
        HINT: The absolute S3 key is wal-e-backups/timeline-921171d4-7c8c-4d75-8b78-d6d3395d167a/basebackups_005/base_0000000700004D50000000A0_12326040/tar_partitions/part_00000012.tar.lzo.
        STRUCTURED: time=2019-06-25T00:29:02.565994-00 pid=22041
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/usr/local/lib/python3.6/dist-packages/wal_e/retries.py", line 87, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.6/dist-packages/wal_e/worker/s3/s3_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/usr/local/lib/python3.6/dist-packages/wal_e/tar_partition.py", line 301, in tarfile_extract
            tar.extract(member, path=dest_path)
          File "/usr/lib/python3.6/tarfile.py", line 2052, in extract
            numeric_owner=numeric_owner)
          File "/usr/lib/python3.6/tarfile.py", line 2122, in _extract_member
            self.makefile(tarinfo, targetpath)
          File "/usr/lib/python3.6/tarfile.py", line 2171, in makefile
            copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
        TypeError: copyfileobj() takes from 2 to 4 positional arguments but 5 were given

```

Investigating.

**Comment by deverant** [comment]
I believe this was fixed in #380 (the fifth argument was added to the copyfileobj that we use in wal-e to be python3.6 compatible).

**Comment by scalp42** [comment]
I see, I switched to wal-g instead but I'm assuming wal-e is behind on pypi.

If anyone sees that, try to install from master to see if it fixes the issue:

```
pip install git+https://github.com/wal-e/wal-e.git
```

**Comment by scalp42** [comment]
Just tested real quick, `master` version works.
