### ISSUE TITLE
Ambigous error for backup-fetch when gpg is poorly configured.

### ISSUE THREAD

**Issue by gvarela** [wal-e/wal-e#8]
I thought this might be related to this issue https://github.com/heroku/WAL-E/issues/45. I was using sudo -u postgres to run the backup-fetch which doesn't set the homedir for gpg correctly (sudo -u postgres -i ... obviously fixes the issue). Easy enough to fix but, it took me a while to figure out because it was erroring on this line https://github.com/wal-e/wal-e/blob/master/wal_e/worker/s3_worker.py#L417 with a runtime error of 'empty file'. I apologize for not grabbing the stack trace but it should be easy to reproduce. Not sure if there is an easier way to detect whether there is a valid file or capture the error that gpg was throwing. Anyway hope this helps someone out.

**Comment by rouge8** [comment]
@fdr I get this error when running `backup-fetch` for encrypted backups without specifying `--gpg-key-id`, possibly the same issue:

```
lzop: <stdin>: not a lzop file
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/opt/wal-e/lib64/python3.5/tarfile.py", line 2283, in next
            tarinfo = self.tarinfo.fromtarfile(self)
          File "/opt/wal-e/lib64/python3.5/tarfile.py", line 1088, in fromtarfile
            obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
          File "/opt/wal-e/lib64/python3.5/tarfile.py", line 1024, in frombuf
            raise EmptyHeaderError("empty header")
        tarfile.EmptyHeaderError: empty header

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/opt/wal-e/local/lib/python3.5/site-packages/wal_e/worker/s3/s3_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/opt/wal-e/local/lib/python3.5/site-packages/wal_e/tar_partition.py", line 267, in tarfile_extract
            bufsize=pipebuf.PIPE_BUF_BYTES)
          File "/opt/wal-e/lib64/python3.5/tarfile.py", line 1592, in open
            t = cls(name, filemode, stream, **kwargs)
          File "/opt/wal-e/lib64/python3.5/tarfile.py", line 1475, in __init__
            self.firstmember = self.next()
          File "/opt/wal-e/lib64/python3.5/tarfile.py", line 2298, in next
            raise ReadError("empty file")
        tarfile.ReadError: empty file

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/opt/wal-e/local/lib/python3.5/site-packages/wal_e/pipeline.py", line 107, in __exit__
            self.stdin.flush()
          File "/opt/wal-e/local/lib/python3.5/site-packages/wal_e/pipebuf.py", line 264, in flush
            self._partial_flush(0)
          File "/opt/wal-e/local/lib/python3.5/site-packages/wal_e/pipebuf.py", line 234, in _partial_flush
            n = os.write(self._fd, cursor)
        BrokenPipeError: [Errno 32] Broken pipe

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/opt/wal-e/local/lib/python3.5/site-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/opt/wal-e/local/lib/python3.5/site-packages/wal_e/worker/s3/s3_worker.py", line 83, in fetch_partition
            raise exc
          File "/opt/wal-e/local/lib/python3.5/site-packages/wal_e/pipeline.py", line 120, in __exit__
            raise exc_type(exc_value).with_traceback(traceback)
          File "/opt/wal-e/local/lib/python3.5/site-packages/wal_e/worker/s3/s3_worker.py", line 78, in fetch_partition
            TarPartition.tarfile_extract(pl.stdout, self.local_root)
          File "/opt/wal-e/local/lib/python3.5/site-packages/wal_e/tar_partition.py", line 267, in tarfile_extract
            bufsize=pipebuf.PIPE_BUF_BYTES)
          File "/opt/wal-e/lib64/python3.5/tarfile.py", line 1592, in open
            t = cls(name, filemode, stream, **kwargs)
          File "/opt/wal-e/lib64/python3.5/tarfile.py", line 1475, in __init__
            self.firstmember = self.next()
          File "/opt/wal-e/lib64/python3.5/tarfile.py", line 2298, in next
            raise ReadError("empty file")
        tarfile.ReadError: empty file

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
```
